### ISSUE TITLE
Amazon EC2 set-up failure

### ISSUE THREAD

**Issue by oleiolei** [Jigsaw-Code/outline-server#10]
First, before you have the script running, it's necessary to install a software called docker on Amazon EC2 Ubuntu system, where docker is not pre-installed.
Second, it doesn't work. After running the script, the server doesn't show any api. It stopped at "starting Watchtower...OK", which is obviously not OK.

**Comment by fortuna** [comment]
Thanks for the feedback, and sorry for your trouble.

When you run `docker ps`, does it show a `shadowbox` container? That's the core of the service.

You can get the JSON needed to set up the Server Manager with
```
cat /root/shadowbox/persisted-state/shadowbox_server_config.json
```
(Don't share the output of that with anyone)

If you'd like to try again, the server installation on EC2 was tested using the image `ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20180126 - ami-66506c1c` (from Community AMIs)

What we did to get it working was:

1.  Under "Configure Security Group", added a "Custom TCP Rule" and a "Custom UDP Rule".  Set the Port Range for both to `1024-65535`, and Source to `0.0.0.0/0`

1. Install Docker
    1. SSH in as user "unbuntu"
    1. `curl -sS https://get.docker.com/ | sh`
    1. `sudo usermod -aG docker $USER`

1. Reboot machine, then SSH again and run:
  `wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh | bash`
  Ignore the error:
```
ERROR: You need to be root to run this script
You have ufw enabled on your machine, please check your configuration to ensure access to high numbered ports.
```
Because "ufw status" requires "sudo", we accidentally think that ufw is enabled when it is not by default

Could you try that and let us know if it still doesn't work?

**Comment by oleiolei** [comment]
Shadowbox is running, but I don't have the JSON file.
![2018-03-21 01_13_23-root ip-172-31-29-92_](https://user-images.githubusercontent.com/37590448/37671703-49976646-2ca7-11e8-8d78-007bbbd17569.png)

**Comment by oleiolei** [comment]
I tried again. It works without any problem if I choose your type of machine and follow your instruction. 
Thank you, fortuna.

**Comment by hybtoy** [comment]
@fortuna 
As I understood, outline will automatically add allowed ports to ufw? 
Now I need to add them manually.

**Comment by arunkumar339** [comment]
Tried Outline installation on ubuntu 16.04 Azure cloud.
The installation script halts at  **Starting Watchtower ......................... OK.**

FYI, I've disabled ufw..
What could be the reason?

**Comment by fortuna** [comment]
@hybtoy : Unfortunately manually installed Outline servers do not open the ports automatically, but that's something we'd like to do (or create a shadowsocks reverse proxy that allows everyone to use a single port). It's a hard problem because each platform has its own way of controlling traffic, sometimes in cloud platforms it's even completely outside the server.

As a workaround you can write a script that find the port numbers with `cat /root/shadowbox/persisted-state/shadowbox_config.json` and opens the port according to the platform you use.

**Comment by arunkumar339** [comment]
Azure Cloud update - Solved. 

An issue with Inbound - Outbound rules. Once we set it properly for ports 1024-65535 it works properly

**Comment by DonaldKBrown** [comment]
I'm having a similar issue, likely from not having UFW even installed on my server. The install hangs after starting the watchtower container. However, I SIGINT the install process and `docker ps` shows that shadowbox is running. But, this is what I get when I try to pull the config information from the container:
`docker exec -it shadowbox cat /root/shadowbox/persisted-state/shadowbox_server_config.json
cat: can't open '/root/shadowbox/persisted-state/shadowbox_server_config.json': No such file or directory`

**Comment by markusmobius** [comment]
I am having the same problem as DonaldKBrown on Ubuntu 17.10 on a HyperV VM. It hangs when starting the watchtower container, shadowbox is running but I cannot get the json configuration.

**Comment by DonaldKBrown** [comment]
Alright, I feel silly. I had inadvertently reinstalled `ufw`. Removing that again fixed my issue. If anyone else has an issue running the installer again after exiting it, you have to stop and remove the previous Docker containers. Run the following commands to do so (**ONLY IF YOU HAVE NO OTHER DOCKER CONTAINERS**)

```
docker stop $(docker ps -aq)
docker rm $(docker ps -aq)
```

**Comment by zl1775** [comment]
@arunkumar339 Could you elaborate on how you solved the problem seeing that ufw was disabled when your first encountered the issue. I am having the same problem although I am running Ubuntu on my own machine.

**Comment by DonaldKBrown** [comment]
I thought my second post explained it. I had reinstalled UFW without realising it. Uninstalling, and therefore disabling, it fixed the issue.On Mar 21, 2018 7:06 PM, zl1775 <notifications@github.com> wrote:@arunkumar339 Could you elaborate on how you solved the problem seeing that ufw was disabled when your first encountered the issue. I am having the same problem although I am running Ubuntu on my own machine.

**Comment by zl1775** [comment]
Oops, I meant to ask arunkumar339. Unless you guys are the same person,
haha.

**Comment by arunkumar339** [comment]
First i thought ufw was blocking the traffic. so i disabled it and tried
the installation again. But still the installation was stuck at "starting
watchtower".

Then i checked networking of the vm at the azure portal and added inbound
rules for the ports (silly me). After that the installatiom proceeded.

**Comment by zl1775** [comment]
I see. This is different from my situations then. I have my server parked
behind a router but it was on the servers DMZ host so all ports should be
open. And I had ufw disabled too. Did you just basically open up the ports
range 1024- 65536?

Thank you!

**Comment by trevj** [comment]
@zl1775 Sorry you've been having problems connecting to your server. Were you able to resolve this?

**Comment by trevj** [comment]
@markusmobius Happy to hear you got connected. Regarding the new access keys you created, they were probably outside the range of 40000-50000. Yes, we currently recommend opening all ports above 1024.

**Comment by trevj** [comment]
@DonaldKBrown Happy to hear you got connected. We are considering a check for the installation script for whether either Docker container already exists.

**Comment by trevj** [comment]
@arunkumar339 Happy to hear you got connected!

**Comment by trevj** [comment]
Seems like most people here got connected, so I'm going to close this. Please open a new issue for any further manual installation woes!
