### ISSUE TITLE
ERROR: Unsupported distribution 'amzn'

### ISSUE THREAD

**Issue by hktalent** [Jigsaw-Code/outline-server#1026]
```
$ uname -a
Linux ip-172-31-27-35.us-east-2.compute.internal 5.10.75-79.358.amzn2.x86_64 #1 SMP Thu Nov 4 21:08:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$ id
uid=1000(ec2-user) gid=1000(ec2-user) groups=1000(ec2-user),4(adm),10(wheel),190(systemd-journal)
[ec2-user@ip-172-31-27-35 ~]$ w
 15:46:25 up 8 min,  1 user,  load average: 0.00, 0.00, 0.00
USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT
ec2-user pts/0    xxx 15:43    1.00s  0.03s  0.00s w


$ bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)"
> Verifying that Docker is installed .......... NOT INSTALLED
> Would you like to install Docker? This will run 'curl https://get.docker.com/ | sh'. [Y/n] y
> Installing Docker ........................... Docker installation failed, please visit https://docs.docker.com/install for instructions.

Last error: # Executing docker install script, commit: 93d2499759296ac1f9c510605fef85052a2c32be

ERROR: Unsupported distribution 'amzn'

Sorry! Something went wrong. If you can't figure this out, please copy and paste all this output into the Outline Manager screen, and send it to us, to see if we can help you.
Full log: /tmp/outline_logNz4
```

**Comment by wolf-allywilson** [comment]
Had the same issue (also on Amazon Linux 2). Fixed it installing docker manually and starting it, then re-ran the setup and it worked fine.

```
# yum install docker -y
# systemctl start docker
```

**Comment by hktalent** [comment]
@wolf-allywilson 
1、install docker
2、in docker install other linux
3、install this

**Comment by miningnome** [comment]
Here's the official solution:

To install Docker on Amazon Linux 2 or Amazon Linux 2023
Update the installed packages and package cache on your instance.


$ sudo yum update -y
Install the most recent Docker Community Edition package.

For Amazon Linux 2, run the following:


$ sudo amazon-linux-extras install docker
For Amazon Linux 2023, run the following:


$ sudo yum install -y docker
Start the Docker service.


$ sudo service docker start
Add the ec2-user to the docker group so that you can run Docker commands without using sudo.


$ sudo usermod -a -G docker ec2-user
Pick up the new docker group permissions by logging out and logging back in again. To do this, close your current SSH terminal window and reconnect to your instance in a new one. Your new SSH session should have the appropriate docker group permissions.

Verify that the ec2-user can run Docker commands without using sudo.


$ docker ps


https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-docker.html
