### ISSUE TITLE
How to properly update Outline server?

### ISSUE THREAD

**Issue by birukoff** [Jigsaw-Code/outline-server#1109]
Github says 1.9.0 is out for a few months now. Yet my Outline Manager reports that my server is still 1.6.1.
I see that the latest docker image (the one the server is running) is still 1.6.1 (https://quay.io/repository/outline/shadowbox?tab=tags&tag=stable)
1) How can I check the actual version of the server?
2) How do I properly upgrade Outline server and keep it up to date?

**Comment by DedMsk** [comment]
+1

**Comment by gitcoinkuang** [comment]
Indeed, this is very unfriendly to the game of cat and mouse. We are still using 1.6.1, so it will be meaningless to update github to 1.9.1. I created it using the command on July 1, 2022, and it is still 1.6.1

**Comment by gitcoinkuang** [comment]
@fortuna

**Comment by c2xusnpq6** [comment]
Any update?

**Comment by DedMsk** [comment]
In install script download container quay.io/outline/shadowbox:stable
Stable 1.6.1 updated a year ago

And in install script we can change url to container
# You may set the following environment variables, overriding their defaults:
# SB_IMAGE: The Outline Server Docker image to install, e.g. quay.io/outline/shadowbox:nightly
But where find this new container )

**Comment by Kami-no** [comment]
Looks like at least docker image publishing automation is broken 😞

**Comment by KourosZanbouri** [comment]
@fortuna is this project abandoned?

**Comment by Kami-no** [comment]
Last commit has been made 4 days ago. I think it's just less public now...

**Comment by gro2bl** [comment]
If you have installed Outline-Server using the official scripts, then the watchtower is [already configured](https://github.com/Jigsaw-Code/outline-server/blob/3698eb712e4aa9176cd594f616c05fe5eaf499cf/src/server_manager/install_scripts/install_server.sh#L18) to update the server image automatically. As @gitcoinkuang already mentioned if you install a fresh copy, you will still see 1.6.1 or 1.6.2 as the version of your server. It seems someone has forgotten to update the version code in shadowbox [package.json](https://github.com/Jigsaw-Code/outline-server/blob/ae8f378cb7bfc549a5aaff16567da2d9603ddbf4/src/shadowbox/package.json#L4) since the version is fetched from [there](https://github.com/Jigsaw-Code/outline-server/blob/ae8f378cb7bfc549a5aaff16567da2d9603ddbf4/src/shadowbox/server/shared_metrics.ts#L21). It's likely you are using the latest version so no worries.

**Comment by Kami-no** [comment]
The problem is that script installed this container: `quay.io/outline/shadowbox:stable`

According to [registry](https://quay.io/repository/outline/shadowbox?tab=tags&tag=stable) it was updated last time 2 years ago.

Do I miss something?

**Comment by Kami-no** [comment]
v1.7.0 has arrived at last!

**Comment by nickolay** [comment]
Just to clear up the confusion, 1.9.0 from the original description referred to the Manager version, the server version at the moment was indeed 1.6.1.

Seems this can be closed, as new server versions are apparently installed automatically. The problem was a year-long pause in releases combined with server vs Manager confusino.
