### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by thebrutish** [Jigsaw-Code/outline-server#1191]
Hi
How many people can connect to an outline server with 1 core CPU and 1 GB of RAM?

**Comment by thebrutish** [comment]
I have unlimited bandwidth
I mean number of multiple connections at the same time from different users

**Comment by rohanmehra20** [comment]
Thank you for reaching out! If this is still an issue for you, please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.
