### ISSUE TITLE
Internet access gets cut off overnight until manually reconnecting Outline VPN

### ISSUE THREAD

**Issue by lolmaus** [Jigsaw-Code/outline-server#1205]
Hi!

If I keep Outline VPN connected overnight, I often find my computer offline in the morning. In order to restore internet access, I have to manually disconnect Outline VPN.

In can reconnect it afterwards and it starts working again... until it eventually fails again.

This is extremely annoying. It stops torrent seeding, stops Folding@Home crunching, makes TeamViewer inaccessible, etc.

I use Outline VPN Client on four devices and all of them are affected:

Windows 10

Windows 11

Linux Mint

Android

I have also tried installing Outline VPN server on two different VPS providers (both custom), and both have this issue.

I've been suffering from this issue for a year — all the time I've been using Outline VPN.

Please help.

**Comment by rohanmehra20** [comment]
Thank you for reaching out! If this is still an issue for you, please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.
