### ISSUE TITLE
Can I install outline-server on Wordpress VPS server?

### ISSUE THREAD

**Issue by alexlii1971** [Jigsaw-Code/outline-server#1206]
Hello,

We have a wordpress server is already working, Can I install outline-server on the Wordpress server?

If yes, is there anything that I should take into consideration so that I can avoid any issue or unexpected behavior?

Thanks

**Comment by daniellacosse** [comment]
Which host are you using?

**Comment by willie-lin** [comment]
Yes, You use It

**Comment by RealmiRoblox** [comment]
What OS on you VPS? If it Linux you can install.

**Comment by rohanmehra20** [comment]
Thank you for reaching out! If this is still an issue for you, please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.
