### ISSUE TITLE
I have been blocked by the server IP, since June this year, there has been a problem of ordinary packet loss

### ISSUE THREAD

**Issue by JamasChuang94** [Jigsaw-Code/outline-server#1208]
I have been blocked by the server IP, since June this year, there has been a problem of ordinary packet loss.
I felt uneasy, so I changed the server ip of the same computer room, and the packet loss was obviously solved, but unfortunately, the redeployed Outline server also frequently lost packets after half a month. Part of the domestic network cannot be accessed. How long is the server IP completely blocked by GFW

**Comment by rohanmehra20** [comment]
Thank you for reaching out! If this is still an issue for you, please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.
