### ISSUE TITLE
500GB or 1TB of transfer?

### ISSUE THREAD

**Issue by psaw** [Jigsaw-Code/outline-server#121]
[DO pricing statement](https://www.digitalocean.com/pricing/) is clear about **1GB of transfer** for "$5/mo droplets" where 
> Only public outgoing transfers are considered for bandwidth billing.

In Outline Manager you've explain DO deployment as "500 GB Transfer , $5 US/Mo".

https://github.com/Jigsaw-Code/outline-server/blob/cd86d505c12669e675f48772e7fa3c1163a1f673/src/server_manager/electron_app/digital_ocean_modifications.ts#L274

I'm not really good in digging down a code, so sorry for my questions if it's a bit lame:

1. Is 500GB a mistake or am I getting it wrong?
2. Do you actually enforce 500GB limit? Or is it just info?

Thank you for your hard work!

**Comment by fortuna** [comment]
1TB refers to download + upload on the server side.

In order to work as a proxy, the Outline Server needs to fetch the data from the destination, and send it to the client. Effectively moving two times the amount of data (once in, once out). From the point of view of the client, you are really seeing half of the total transfers. That's why we show 1TB / 2 = 500GB.

**Comment by psaw** [comment]
> Only public **outgoing transfers** are considered for bandwidth billing.

Doesn't that mean fetching data from the destination up to the Server is free? And that seems OK, because usually cloud providers don't charge for ingress traffic.

**Comment by manizand** [comment]
> Effectively moving two times the amount of data (once in, once out)
@fortuna 

https://www.digitalocean.com/community/tutorials/digitalocean-bandwidth-billing-faq

**Comment by fortuna** [comment]
It seems [DO's policy](https://www.digitalocean.com/pricing/) has changed since we wrote the code:

> Only public outgoing transfers are considered for bandwidth billing. Transfer limits are calculated by pooling the transfer from all droplets on the account. Overages above pooled transfer will be charged at a rate of $0.01/GB.

Thanks all for letting us know!

If they are only charging the outgoing transfers, then we shouldn't double-count anymore. @sandrigo could you confirm? In that case, we have a bug and need to update the code to say 1TB.

**Comment by sandrigo** [comment]
Correct. This needs to be updated on:
- Outline Server Manager application startup screen
- Total bandwidth number in the Outline Manager user management screen
- The "How much does Outline cost?" question on the Outline Help Center

**Comment by fortuna** [comment]
Website is now fixed and live. The manager is fixed, and the change will go live in the next release.

**Comment by manizand** [comment]
> Assuming an average usage of 5 GB of data transfer per user, a plan of $5 USD per month would allow for 200 concurrent users, making the cost per user just 5 cents per month

2.5 cents is correct 😄

**Comment by fortuna** [comment]
This has been released a while ago.
