### ISSUE TITLE
websites take a long time to load

### ISSUE THREAD

**Issue by Frederick-huizinga** [Jigsaw-Code/outline-server#1248]
Hi!

I have a VPS (OVH) and I'm installing the outlineVPN. It works and I can connect but when I try opening a website it takes very long (7/8 secondes) does anyone have an idea why it takes so long?

The problem is on windows 11 and android. I tried wireguard (after a fresh reinstall) and that works fine, please let me know

**Comment by rohanmehra20** [comment]
Thank you for reaching out! If this is still an issue for you, please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.
