### ISSUE TITLE
Filtering in Iran causes to not to able to create new ACTIVE servers on AMAZON LIGHTSAIL SERVERS or DIGITAL OCEAN !

### ISSUE THREAD

**Issue by idevsoftwaregroup** [Jigsaw-Code/outline-server#1253]
Filtering in Iran causes to not to able to create new ACTIVE servers on AMAZON LIGHTSAIL SERVERS or DIGITAL OCEAN ! 

I have amazon lightsail premium account and digital ocean too and I am from Iran . it is about 3 days ago when I wanted to create new servers I did it but new servers were not able to connect to the Servers by Outline Client on any of internet providers like MTN IRANCEL  or MCI . so what should we do ?

**Comment by Rolfff** [comment]
Choose a small hosting company to install your Outline server. With an IP range that is not often used in Iran.

**Comment by Rolfff** [comment]
And make sure that your user does not consume more than 10 GB of data per month. The regime obviously notices the data traffic. My server has been blocked for a few days. This worked for about two months.

**Comment by idev-software-group** [comment]
I did it so many times but in every time Filtering will do its duty and filters every Server I just created for a few days ... I need a great and more complex than your solution @Rolfff . any way thanks

**Comment by vim345** [comment]
I installed outline server on my home server outside Iran and opened the port for my brother in Iran. He was able to use it for a while until today morning. I'm not too sure what happened today. I just know that my IP isn't blocked. Because he can connect to my SSH server on the same host. They block SSH authentication. So if one disabled SSH authentication, it's possible to use the tunnel. However it's not the safest option. I wonder if it's possible to disable outline authentication as well? I suspect they are able to block the packets that are used for authentication in outline as well.

**Comment by Rolfff** [comment]
I can confirm that none of my outline servers are reachable from Iran anymore. Ping is possible. Outline is not.

**Comment by rezarms** [comment]
I have tried outline in Aws,Digital ocean,Kamatera ,hetzner and ionos nut none of them worked.
Only Microsoft servers are intermittent for me which are expensive for bandwidth.
I tested connectivity using powershell net-tcpconnection and it shows there is a connection to those servers .
I also setup a webserver on those server and I was able to reach them from Iran.
It looks like that protocol gets blocked not IPs . If the protocol is blocked why is it working on Azure ?
Or combination of protocol+IP get blocked !

**Comment by rezarms** [comment]
I have tried OpenVpn, Cisco anyconnect and wireguard  in above cloud providers and no success.
In Azure shadowsocks works but I'm not sure why it's not working in other Cloud providers.
 If shadowsocks protocol is blocked it shouldn't work in Azure either.

**Comment by Rolfff** [comment]
Can you confirm that Outline is working again?

**Comment by rezarms** [comment]
In Aws Ireland for some IPs still works

**Comment by rohanmehra20** [comment]
Thank you for reaching out! If this is still an issue for you, please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.
