### ISSUE TITLE
Accept failed: accept tcp [::]:<port>: accept4: too many open files

### ISSUE THREAD

**Issue by amirbahojb76** [Jigsaw-Code/outline-server#1269]
i run docker logs shadowbox and get Accept failed: accept tcp [::]:<port>: accept4: too many open files this error ! how can i fix this error ?

**Comment by rohanmehra20** [comment]
Thank you for reaching out! If this is still an issue for you, please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.
