### ISSUE TITLE
How to make outline sends and recieves data through a specific port on localhost

### ISSUE THREAD

**Issue by arashammm** [Jigsaw-Code/outline-server#1276]
Hello there

Special thanks to Jigsaw and other contributors of this great project.

I try to use outline on a relay machine in combination with ssh tunnel. my setup looks like this :

1. A distant machine connecting to the relay machine using ssh tunnel
2. The relay machine listens to localhost:4000 to send data to the distant machine
3. Outline configured on the relay machine 
4. I need the outbounded traffic of Outline goes through localhost:4000 (not the main network interface of the relay machine)

How can I achieve this?

**Comment by arashammm** [comment]
any thoughts?

**Comment by rohanmehra20** [comment]
Thank you for reaching out! Please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.
