### ISSUE TITLE
After the latest Debian 11 server update Outline server can't be installed anymore via the script

### ISSUE THREAD

**Issue by zeretrelle** [Jigsaw-Code/outline-server#1296]
After updating a clean Debian 11 server and trying to run the installation script, it fails to do it

Before that it used to work fine

The output of the installation script:

https://pastebin.com/4sWDhvEJ

Ubuntu 22.04 works fine

Kind regards,
Alex

**Comment by rohanmehra20** [comment]
Thank you for reaching out! Please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.
