### ISSUE TITLE
Firewall blocked on Oracle VPS

### ISSUE THREAD

**Issue by peterhou19** [Jigsaw-Code/outline-server#1297]
Hi, I'm trying to setup Outline on Oracel VPS, however, with multiple tries and settings, I always get blocked by the firewall. 

I have added all traffic in the subnet setting, no good. 
Tried to open up all the ports inside the console, still no good. 

Please advise my next steps should be to address this issue. 
Thank you.

**Comment by rohanmehra20** [comment]
Thank you for reaching out! If this is still an issue for you, please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.
