### ISSUE TITLE
NOT RUN OUTLINE AFTER LAST UPDATE!

### ISSUE THREAD

**Issue by bardia13s** [Jigsaw-Code/outline-server#1300]
HI PLEASE HELP TODAY AFTER UPDATE OUTLINE MANAGER FROM VERSION 1.14 TO V1.14 , NOT RUN MY outline manager anymore , I restart vps restart docker but not fix I have alot of customers how somebody help me ?

**Comment by bardia13s** [comment]
I have another problem in last update , my bridge server  not connect to my main server outline anymore how can I fix this problem ?

**Comment by rohanmehra20** [comment]
Thank you for reaching out! Please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.
