### ISSUE TITLE
Failure starting Watchtower when adding new server

### ISSUE THREAD

**Issue by moein-barzegaran** [Jigsaw-Code/outline-server#1301]
Hello, 
I got this log when run the script of Outline manager for adding Outline into my server.

```
Sorry! Something went wrong. If you can't figure this out, please copy and paste all this output into the Outline Manager screen, and send it to us, to see if we can help you.
Full log: /tmp/outline_logQWo
Unable to find image 'containrrr/watchtower:latest' locally
docker: Error response from daemon: error parsing HTTP 408 response body: invalid character '<' looking for beginning of value: "<html><body><h1>408 Request Time-out</h1>
Your browser didn't send a complete request in time.
</body></html>
".
```

**Comment by rohanmehra20** [comment]
Thank you for reaching out! Please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.
