### ISSUE TITLE
Access key not valid. iOS app, version 1.10

### ISSUE THREAD

**Issue by legend-of-today** [Jigsaw-Code/outline-server#1304]
Tested it on the previous version, 1.9, still works like a charm. Tested the mac app, haven't updated it to the latest build though, no issues there. However, v1.10 on my other devices (reinstalling the app and issuing new access keys did not resolve anything) still deems any access key invalid when trying to connect to the sever. Since it is impossible to downgrade the app version on iOS, it has become quite an inconvenience. I hope a fix will be issued in the near future.

**Comment by rohanmehra20** [comment]
Thank you for reaching out! Please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.

**Comment by legend-of-today** [comment]
Old server still won't budge on the 1.10 version across all platforms. Moved to a new hosting (which is cheaper and better, so whatever), now everything works like a charm.
