### ISSUE TITLE
Where is shadowbox logs?

### ISSUE THREAD

**Issue by KOT4N** [Jigsaw-Code/outline-server#1308]
I install shadowbox and have some unexpected troubles. Where I can find logs?

**Comment by KOT4N** [comment]
My problem:
I can't connect to server. I install it on new machine - same, I change provider - same, I change vps hosting - same.

**Comment by KOT4N** [comment]
ok I found logs but it useless, bruh

**Comment by ilovefood2** [comment]
where is log located ?

**Comment by rohanmehra20** [comment]
Thank you for reaching out! Please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.
