### ISSUE TITLE
HELP ME help me     How to solve this problem

### ISSUE THREAD

**Issue by yujia1256** [Jigsaw-Code/outline-server#1310]
<img width="1680" alt="屏幕快照 2023-03-11 18 45 41" src="https://user-images.githubusercontent.com/78677159/224480388-acf2bb07-3ef5-41c2-912b-3bca851afeed.png">
<img width="1680" alt="屏幕快照 2023-03-11 18 45 57" src="https://user-images.githubusercontent.com/78677159/224480401-4b3a7d73-2224-4e57-a689-b4afb9a70c80.png">

**Comment by reberu** [comment]
> <img alt="屏幕快照 2023-03-11 18 45 41" width="1680" src="https://user-images.githubusercontent.com/78677159/224480388-acf2bb07-3ef5-41c2-912b-3bca851afeed.png">
> 
> <img alt="屏幕快照 2023-03-11 18 45 57" width="1680" src="https://user-images.githubusercontent.com/78677159/224480401-4b3a7d73-2224-4e57-a689-b4afb9a70c80.png">

It seems to be the docker problem.
Troubleshoot solution here by link https://docs.docker.com/desktop/troubleshoot/overview/

**Comment by rohanmehra20** [comment]
Thank you for reaching out! Please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.
