### ISSUE TITLE
Metrics Issue

### ISSUE THREAD

**Issue by SadeghSalman** [Jigsaw-Code/outline-server#1317]
Assume there is enough space to record Usage data for each key. How to change usage data period from 30 days to one year or other values?

The problem that has arisen is that after one month (30-day period), the usage of each key decreases until it reaches zero, and the disabled user can use it again. It is also difficult for the user to get a new key after every month. It is also difficult for the admin to delete the expired keys. What is the solution?

**Comment by SadeghSalman** [comment]
Hello Jigsaw Team,

Is there any Temporary solution to fix this issue? As I found in documents all metric collected by Prometheus in a certain period. How can we get access to these metrics via api?

**Comment by SadeghSalman** [comment]
Is there any update for this request?

**Comment by maddyhof** [comment]
Thanks for reaching out! To make sure we're understanding your request, it sounds like you want to: 
- Change the interval for the data limit on a key to some number other than 30 days
- Access data usage metrics through the server management API rather than Prometheus 

Additionally, you mention needing to send out new keys every month and delete expired keys. The current implementation does not involve setting an expiration date, only an amount of data available within that floating 30-day window. Are expiration dates something you're asking for as a new feature?

**Comment by linehman** [comment]
Hi there @maddyhof . I was reading through the github issues and noticed that many users want these features. If the development team considers adding them it would make the outline more convenient to use and manage.

In summary, having the ability to set a custom expiration date for each user and a traffic reset button for any user are two of the most requested features. Of course if the user for example expires in three months, then traffic should also be calculated for three months, instead of 30 days.

Another thing I noticed is the gradually decreasing trrafic usage after 30 days that is very confusing. Having a button for resetting this to zero would be easier to understand.

Kind regards.

**Comment by maddyhof** [comment]
Thanks so much for the clarification. We do indeed have existing open issues for the things you've requested. 

- Reset data limits to 0 #1371 
- Allow fixed windows for measuring usage #1288 
- Set expiration date for a key #1318 

I think those should cover all of your requests, in which case I can close this ticket as a duplicate. But if I left anything out please let me know.
