### ISSUE TITLE
outline-server keeps being blocked after a while using in china 

### ISSUE THREAD

**Issue by ilovefood2** [Jigsaw-Code/outline-server#1319]
I created a few outline servers on aws before going to china
First a couple weeks, it was working fine. then the one I kept using was not responding anymore, I can't ping even. but from aws side, I can see it's working fine. So that proved that it was blocked. 
So I started using next one, soon a few days after the second one is blocked as well. Then the 3rd one too got blocked after using it a few days.

It seems outline server is not working well in China. Is there any fix for that?

**Comment by xfisbest** [comment]
if you are able to ssh into servers, have you tried ssh tunneling?
ssh -L 127.0.0.1:1080:127.0.0.1:outlineporthere

**Comment by TAMSHUI** [comment]
I faced the same issue in the last few weeks. but I deployed Outline Server on Azure Southeast Asia region. and I tried to re-allocate a new public IP address to temporarily fix this issue, but after a few days it happened again.
PS: when my outline client tries to connect to outline server, it is shown time out, and if I try to SSH to the outline server it also fails to connect.

**Comment by rohanmehra20** [comment]
Thank you for reaching out! Please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.

Thank you for reaching out! Please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.

**Comment by rohanmehra20** [comment]
Thank you for reaching out! Please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.

**Comment by hklcf** [comment]
try to use prefix to bypass protocol allowlists
https://www.reddit.com/r/outlinevpn/wiki/index/prefixing/

**Comment by dazuiba** [comment]
> try to use prefix to bypass protocol allowlists https://www.reddit.com/r/outlinevpn/wiki/index/prefixing/
> 
> my result: over 2 month w/o any problem in china

is this solution  goting to work?

**Comment by murka** [comment]
@dazuiba, let's try use TLS ClientHello prefixing for bypass blocking.

**Comment by dazuiba** [comment]
> @dazuiba, let's try use TLS ClientHello prefixing for bypass blocking.

It's 4 days after setup prefix ,  not banned again.  

Thank you!

**Comment by ilovefood2** [comment]
> > @dazuiba, let's try use TLS ClientHello prefixing for bypass blocking.
> 
> It's 4 days after prefix was setup , not banned again, every thing goes well.
> 
> Thank you!

how is it now? did u get blocked after a couple weeks?

**Comment by dazuiba** [comment]
Never blocked again.

**Comment by ilovefood2** [comment]
@dazuiba which prefix did u use from table? 
TLS ClientHello
TLS ServerHello
TLS Application Data 

Is it TLS ClientHello ? 

Thank you
