### ISSUE TITLE
Amazon server shuts down after 24 hours 

### ISSUE THREAD

**Issue by Tolik00** [Jigsaw-Code/outline-server#1347]
Twenty-four hours after I connect the Amazon server to outline, it disconnects and writes that it cannot connect to the server.

I don't make any changes to the server or outline. What could be the problem?

**Comment by maddyhof** [comment]
Hi @Tolik00. It's hard to be certain, but there's a possibility your server is getting blocked (e.g. by the government or ISP or cloud provider). If you'd like help looking into this, please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.

**Comment by rohanmehra20** [comment]
Thank you for reaching out! If this is still an issue for you, please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.
