### ISSUE TITLE
Access key id no valid on Windows 11 but the same server is connected from other devices

### ISSUE THREAD

**Issue by dpevunov** [Jigsaw-Code/outline-server#1355]
Hello!

I cannot connect to my outline server from Windows 11 PC. The error is "Access key is not valid". But I can connect to that server using the same key from iPhone and other PC with Windows 10. This means that the access key seems to be valid. Could you please help me to resolve the problem?

Thanks and have a nice day!

wbr,
Denis

**Comment by maddyhof** [comment]
Thank you for reaching out! Please contact us at [support.getoutline.org](https://support.getoutline.org/) and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org ](https://support.getoutline.org/s/)for access to help articles and more.

**Comment by dpevunov** [comment]
Hello,

Ok, wrote at [support.getoutline.org](https://support.getoutline.org/). Hope for the response.

wbr,
Denis

**Comment by dpevunov** [comment]
I don’t know what is completed. The issue is not resolved. We are discussing it in emails. С уважением,Денис Певунов17 июля 2023 г., в 17:53, maddyhof ***@***.***> написал(а):﻿
Closed #1355 as completed.

**Comment by maddyhof** [comment]
Sorry for the confusion. I understand that your problem is not yet resolved. Now that you're discussing it with the Support team, I've closed this GitHub issue and will let them take it from here.
