### ISSUE TITLE
API - /metrics/transfer

### ISSUE THREAD

**Issue by prok0l** [Jigsaw-Code/outline-server#1406]
The function {api_url}/metrics/transfer does not work correctly. Similarly, determining traffic consumption in the outline manager does not work correctly. Each time it is called, a unique value is taken. At first it might be 40MB, and then suddenly 31MB. The function gives only approximate values.
![image](https://github.com/Jigsaw-Code/outline-server/assets/73758053/008f247d-0800-4ef4-9648-1bffc33f7097)
![image](https://github.com/Jigsaw-Code/outline-server/assets/73758053/ab405a8c-e891-43e0-af6d-b493681eb145)
![image](https://github.com/Jigsaw-Code/outline-server/assets/73758053/cdc955b3-44be-4477-aeb6-d46b1f430d78)

**Comment by maddyhof** [comment]
Thanks for reaching out! How much time elapsed between the various screenshots you took? The traffic is measured in a 30-day floating window, so the amount can fluctuate as usage changes each day. We have open feature requests for fixed windows (#1288) or saving the data indefinitely (#1321). Is that what you'd be looking for?

**Comment by prok0l** [comment]
1) The time between requests is a couple of minutes
2) I expect to receive a static value

**Comment by maddyhof** [comment]
Given the rolling window, a shift in either direction by a few megabytes is expected behavior. We don't expect static values, since the start time of the window is constantly changing based on the current time. We have open feature requests for static values, for example #1288. If you want the ability to specify start & end dates in order to receive a static value, that would be a new feature request, and I can update this issue to reflect that request. Please confirm.

**Comment by prok0l** [comment]
ok, if the error is a couple of megabytes it’s not critical
