### ISSUE TITLE
PoC: non-increment unique keyId

### ISSUE THREAD

**Issue by murka** [Jigsaw-Code/outline-server#1468]
Actual problems provided by auto-increment keyId:
- id is not reusable. For example: I create 3 keys: 1,2,3 and delete 2, the new key id is 4, and 2 is undefined.
- We are already use uuidv4 to create Prometheus metrics. So, why not combine, and use one id for them? See https://github.com/Jigsaw-Code/outline-server/blob/6c433ed6fa6bc37ab6107e0216131069e83c81be/src/shadowbox/server/server_access_key.ts#L172
- This does not allow import/export keys. See https://github.com/Jigsaw-Code/outline-server/pull/1273#discussion_r1437272940

So, let's allow create AccessKeyId on demand, or create uuidv4 if id prop is not provided. Subsequently, this will then allow for an infrastructure where keys can be synchronised between servers.

**Comment by jyyi1** [comment]
Hi @murka , both PR have been merged. Did this solve your issue? If so, please feel free to close this issue. Thanks.

**Comment by murka** [comment]
Hi, there!

Nope, the problem is not solved. So, I think I can PR-draft FYI.

**Comment by jyyi1** [comment]
Thanks @murka for the clarification. Yes, please feel free to draft new PRs. Thanks for the contribution!

**Comment by fortuna** [comment]
I'm trying to understand the need here.
What's wrong with the Ids not being reused? Ids are not supposed to be reused.

With https://github.com/Jigsaw-Code/outline-server/pull/1473 you can import keys and use your own ID system.

Prometheus actually uses the key id, not the metricsId. metricsId is used for opt-in metrics to count unique keys. It's confusing though...

We use sequential numbers because we display the ID in case the key doesn't have a name "Key $ID", which is helpful in distinguishing the keys. UUIDs are less user friendly in that sense.

**Comment by murka** [comment]
So, you're all right, I think I can deprecate this PoC.
