### ISSUE TITLE
InvalidServerCredentials

### ISSUE THREAD

**Issue by Antirecord** [Jigsaw-Code/outline-server#1543]
Hello! 
I have a shadowbox deployed in Docker. Recently, some users have had problems (about 20 people use it in total), the following error occurs in the Outline application (at least on iOS):
InvalidServerCredentials

What could be causing this, and can it be fixed somehow? I would send the logs, but I don't see any errors in shadowbox.

**Comment by taublast** [comment]
The funny part is that Windows client still works okay, and Mac/Android/iOS outline clients of same version (1.13.x) now get this error for any old/new credentials working fine with Windows client. So i would say this looks like an Outline client problem, not this server's. Totally caused by VPN blockers..

**Comment by Bukmopbl4** [comment]
Same problem. When setting up a server on DigitalOcean, everything works perfectly right away. Doing the same setup on GoDaddy, I can't connect either from an iPhone or a MacBook. The necessary ports are accessible remotely. Haven't figured out the cause yet.
