### ISSUE TITLE
Failed to find active client

### ISSUE THREAD

**Issue by mcipovic** [Jigsaw-Code/outline-server#1590]
Hello,

I have this strange issue: this error always repeats on the server. I found it in the docker logs
My VPN server has ~33k+ keys and API is very slow to react.

The VPS machine is hosted on Digital Ocean, have 8cpu cores, and 16GB of ram

Thanks

**Comment by sbruens** [comment]
Would you be able to share more logs so we can see the context in which this is happening? Feel free to redact PII.

**Comment by sbruens** [comment]
Thanks @oplexz, that's very helpful. @fortuna and I were able to reproduce it just now and found the source of the issue. The summary is that we try to calculate the new tunneltime metric for closed unauthenticated requests, which then can't be found because they are not authenticated. These should be excluded.

Note this is a warning, not an error. It does not impact your metrics. But we should address the warning. I created https://github.com/Jigsaw-Code/outline-ss-server/pull/209 to address it. Thanks for reporting this and helping us find the root cause!

**Comment by mcipovic** [comment]
@sbruens Here is my log from the server. Is there a way I can delete non-used keys in one go as I have like 35k keys generated, maybe that is slowing down the server. I can't find the command for that.

Thanks,
Marko
[log.txt](https://github.com/user-attachments/files/16989167/log.txt)

**Comment by sbruens** [comment]
@mcipovic We don't have a dedicated endpoint to delete unused keys, but you can do this using the Access Key Management API: https://github.com/Jigsaw-Code/outline-server/tree/master/src/shadowbox#access-keys-management-api. You can combine some calls, but you should be able to do this by listing keys, checking each data usage (this is bytes used for the last 30 days), and deleting them based on the result.

**Comment by sbruens** [comment]
PS: If you're familiar with Prometheus, you can also use that to query more precise data usage for access keys and then make deletion calls based on whatever list of keys you found.
