### ISSUE TITLE
Does outline manager leverage multicore cpu?

### ISSUE THREAD

**Issue by teddychan** [Jigsaw-Code/outline-server#161]
We are running on GCP, using n1-standard-1 with 1CPU 3.75G Ram.

Sometimes we hit 100% CPU loading (20 users), few of them having the video meeting at that time.

Wanna know if outline manager leverages multiple CPU?
say 
n1-highcpu-2 | High-CPU machine type with 2 virtual CPUs and 1.80 GB of memory?

**Comment by fortuna** [comment]
We currently use https://github.com/shadowsocks/shadowsocks-libev on the server. I'm not sure whether that uses multiple CPUs. Given it uses libev, maybe not, but @madeye would know for sure. You may want to ask in their repository.

We do start one instance of ss-server for each access key. Since they are separate processes, thay can run on different CPUs.

**Comment by fortuna** [comment]
@teddychan Are you using one access key per user, or are they all sharing the same access key?

**Comment by teddychan** [comment]
@fortuna Every user is using its own key.
So 10 users will have 10 different keys.
Does it help?

**Comment by Soghra124** [comment]
Good

**Comment by Soghra124** [comment]
``

**Comment by fortuna** [comment]
This thread is outdated and no longer reflects the state of the server. We've migrated to our own Shadowsocks implementation a long time ago.
