### ISSUE TITLE
ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by Dimit77** [Jigsaw-Code/outline-server#1611]
I visit every website and get ERR_EMPTY_RESPONSE response when outline client conected and outline server no err logs. I can ping website through
ping :
ping : C:\Users\Dimit>ping -t 8.8.8.8
Обмен пакетами с 8.8.8.8 по с 32 байтами данных:
Ответ от 8.8.8.8: число байт=32 время<1мс TTL=64
Ответ от 8.8.8.8: число байт=32 время<1мс TTL=64
Ответ от 8.8.8.8: число байт=32 время<1мс TTL=64
Ответ от 8.8.8.8: число байт=32 время<1мс TTL=64
Ответ от 8.8.8.8: число байт=32 время<1мс TTL=64
Ответ от 8.8.8.8: число байт=32 время<1мс TTL=64

OS: windows 10, 11
Server managed manually on ionos.de (ubuntu)
Server in Germany or GB, client in Russia
log in attachment
[log.txt](https://github.com/user-attachments/files/17429573/log.txt)

**Comment by jyyi1** [comment]
Thank you for reaching out! Please contact us through the application on the device where you’re experiencing this issue – or at [support.getoutline.org](https://support.getoutline.org/) – and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org](https://support.getoutline.org/s/) for access to help articles and more.
