### ISSUE TITLE
VPS' IP Address will be blocked in Iran and China after using Outline VPN

### ISSUE THREAD

**Issue by kalhori124** [Jigsaw-Code/outline-server#193]
Recently, Iran and China's firewalls detect Outline VPN protocol then IP address of the server will be blocked after a while ( it depends on volume of traffic between Clients and server ).

Unfortunately, after blocking I cannot connect to the server even with SSH protocol and I have to delete the VPS and create a new VPS with new IP address ! I created and deleted 4 VPSs in a week !

Is it possible to obfuscate Outline VPN protocol ?

**Comment by Tintac-CN** [comment]
The GFW has acquired the means to precisely detect the shadowsocks server for a while.You should try some new protocols like VMESS and shadowsocks with AEAD. But once you cost too much bandwidth on single IP, your IP will be banned for sure. So the best way is try use CDN to transfer data to your server(shadowsocks in websocket, V2ray support this feature), I don't think they will ban all these IP using by some major CDN provider.

**Comment by kalhori124** [comment]
Thank you for VMESS ( v2ray ) suggestion, Do you know any CDN provider that works as a relay for VPN protocols ?

**Comment by kalhori124** [comment]
Hi @fortuna 
Do you have any plan to obfuscate Outline VPN protocol ?

**Comment by 4044ever** [comment]
Just wondering, standalone Shadowsocks using some sort of selective routing based on GFW blocking. When I go to (China blocked) google and type 'my IP' then google returns my VPN IP. But when I go to MyIP.cn it returns my current network IP.

Outline does not have that feature. Wouldn't that help to avoid detection?

**Comment by studentmain** [comment]
All of my server use 'global mode' and works well for a years

4044ever <notifications@github.com> 于 2018年7月11日周三 14:37写道：

**Comment by 4044ever** [comment]
> All of my server use 'global mode' and works well for a years

What good is a server when you can't connect to it? The initial question was also about blocked access, not unblocked access.

Questions remains open.

**Comment by Tintac-CN** [comment]
Cloudflare can relay websocket net flow, some chinese cloud provider like
Aliyun can even relay H2 network data.However, acquiring an CDN in china
may need some illegal methods to avoid the identification check.

kalhori124 <notifications@github.com> 于2018年7月10日周二 上午1:44写道：

**Comment by 4044ever** [comment]
@Tintac-CN 
Are there any instructions for setting up Cloudflare for Outline? This sounds very interesting. 

If possible in English, 但是中文也可以

(this would be perfect for a new topic)

**Comment by Tintac-CN** [comment]
Using CDN as data transporting methods is impossible for Outline, because
outline doesn't include websocket feature right now.The CDN can only
retransmit  formal web data，like H2，websocket.

4044ever <notifications@github.com> 于2018年7月12日周四 下午6:21写道：

**Comment by fortuna** [comment]
We want to consider other protocols, but as I mentioned before, it's unclear to us if the protocol is the reason for the blocking. Would a different protocol make any difference? You will still have lots of random-looking traffic going to a single IP address.

In any case, we see the value of allowing proxying over HTTPS and Websockets, and we have an internet standard proposal to be discussed at the IETF next week that allows web proxies to proxy UDP or IP over Websockets. People interested are welcome to follow: https://datatracker.ietf.org/doc/draft-schwartz-httpbis-helium/

**Comment by kalhori124** [comment]
@fortuna I have tested three other protocols ( Stunnel , Txthinking/Brook and OpenConnect ) and there isn't any problems except OpenConnect protocol that need to change TCP/UDP port from 443 to 800 in order to work.

But when I use Outline VPN and use it with huge volume bandwidth, the firewall will autmatically blocked the IP address of the server and I cannot connect to the server ( even SSH protocol ) but the server is accessible from other countries.

I realize that the firewall will unblock the IP address of the server automatically after three days and Outline VPN will be available to use but if I use it again with huge volume bandwidth it will be locked again !

**Comment by kalhori124** [comment]
@fortuna I am using Stunnel for five years and my server never blocked ! Is it possible to use Stunnel in Outline VPN ?

**Comment by studentmain** [comment]
You mean huge volume bandwidth with stunnel not get blocked? Thats sounds
good. I want know how huge bandwidth, I just downloaded about 70GB file
over shadowsocks at about 20Mbps, everything OK (then I run out of my
server traffic), my ISP is CERNET, server runs v2ray. If need, I'll test at
China Telecom next month.

Collect block report could help us understand how GFW works.

stunnel socks vpn sounds great, it has built in authentication. The problem
is this project already use shadowsocks protocol...

kalhori124 <notifications@github.com> 于 2018年7月15日周日 03:02写道：

**Comment by VictoriaRaymond** [comment]
Just saw [V2Ray](https://www.v2ray.com/) mentioned here, and come for some advertisement 😉

V2Ray provides transport methods such as WebSocket and HTTP/2, that can transfer data through a third-party gateway. A common usage is to tunnel through CloudFlare using WebSocket, when proxy client can't talk to proxy server directly. V2Ray's transport supports both Shadowsocks and VMess (its own protocol), and other protocol like MTProto proxy.

We believe VMess is better than Shadowsocks for the following reason:
1. it supports multi-user on a single TCP port. 
1. it forces UDP over TCP, i.e. server opens only TCP ports. It is highly suspicious when a server opens both UDP and TCP protocol on the same port number, like what Shadowsocks does.
1. VMess can leverage TLS to provide forward secrecy, when privacy is a concern. Otherwise, VMess uses PSK encryption in favor of less latency.
1. We are adding random padding to VMess protocol. This will be done in the next few releases. We are releasing on weekly basis btw.

@fortuna as you are interested, V2Ray also provides [routing](https://www.v2ray.com/en/configuration/routing.html) based on domain, IP and other factors. With this feature, V2Ray can be configured to bypass domestic IPs, or tunnel traffic to multiple proxy servers based on the destination. For example, if you want to watch Netflix through a US proxy, and also BBC via a UK proxy at the same time, this can be easily done in V2Ray (while it is difficult is Shadowsocks).

**Comment by fortuna** [comment]
@kalhori124 Thanks for the information. That gives us a little more understanding on how the blocking operates.

* Stunnel: I'm surprised that they block Shadowsocks, but not TLS. That would mean they can put the two protocols in different buckets. I wonder if it's because we have the UDP port open. We don't return replies to invalid requests (so it doesn't give it away it's open), but I wonder if there's some ICMP going on. Exploring having UDP closed and investigating the ICMP packages is something we can try.
If TLS works, I imagine simple secure web proxies (over HTTPS) should work too. My team also created https://github.com/caddyserver/forwardproxy. Have you tried that?

* OpenConnect: It seems this is also a TLS-based protocol, which is another sign TLS is not being disturbed.

* Brook: What protocol did you use with it?

**Comment by fortuna** [comment]
@VictoriaRaymond, thanks for the input!

1. Multi-user on single port is definitely we want to have. I have an experimental version of that as a fork of go-shadowsocks2 that I'll look into upstreaming.

1. I agree on UDP traffic being suspicious. I wonder if opening a different port for UDP would mitigate  the issue. We can stop using UDP, but I believe there's a performance cost to that. Unlike system proxies, we operate at the IP layer, intercepting all the system traffic. We can't connect to domain names like SOCKS and need to proxy DNS requests.

1. Forward secrecy is great. That's definitely something we wish to have. However, as far as I can tell, you can only get forward secrecy if you have a handshake, and handshakes are usually easy to detect and block. Maybe VMess is not blocked now, but a handshake fingerprint could make it very easy to block if it gets widely adopted.
On Outline, one way to work around the forward secrecy issue is to keep generating new access keys that you use for a short period of time.

1. What attacks do you have in mind? Padding can have significant impact on performance, but it may be an effective measure against fingerprinting the handshake. :+1: 

Good to know about your routing features. The challenge to us is that we operate at the IP level, so it's hard to do routing based on the domain. Does V2Ray support intercepting all the traffic or does it work as a system proxy? If you operate at the IP layer, how do you route based on domains?

**Comment by VictoriaRaymond** [comment]
> Maybe VMess is not blocked now, but a handshake fingerprint could make it very easy to block if it gets widely adopted.

TLS is an optional feature for those who require forward secrecy. The bare VMess protocol works with PSK and doesn't have handshake fingerprint.

> What attacks do you have in mind? Padding can have significant impact on performance, but it may be an effective measure against fingerprinting the handshake.

As TLS (or HTTP2) gets more and more popular, we assume it will be more often Shadowsocks (or VMess) carries TLS traffic. Shadowsocks itself doesn't have fingerprint, but TLS does. For example, the ClientHello message is around 160 to 170 bytes long, and ServerHello message is 70 to 75 bytes ([reference](http://netsekure.org/2010/03/tls-overhead/)). Shadowsocks's header is somewhat 30 bytes long. Combining these factors, one may tell that this TCP connection uses an unknown protocol to carry TLS traffic. In such case, the connection (or IP) may be blocked by the firewall without knowing whether it is truly Shadowsocks or not.

To mitigate such issue, V2Ray introduces an multiplexing feature, named [Mux.Cool](https://www.v2ray.com/developer/protocols/muxcool.html) (Chinese only, sorry), which combines multiple TCP connections into one. The fingerprint of TLS gets hidden in the master connection.

We also realize that the fingerprint may get exposed when there is only one TLS connection at a time. That's why we are experimenting the random padding feature.

> Does V2Ray support intercepting all the traffic or does it work as a system proxy?

It works as a system proxy, similar to Shadowsocks. Some other developers uses [tun2socks](https://github.com/eycorsican/go-tun2socks) to intercept all traffic and then proxy them through V2Ray. I guess you already familiar with that part.

> If you operate at the IP layer, how do you route based on domains?

There is one difficulty with IP tunnel. When a domain gets DNS poisoned, IP based proxy will fail. V2Ray (if configured) intercepts HTTP and TLS connection, and then tries to correct the destination address based its handshake info.

**Comment by fortuna** [comment]
@VictoriaRaymond Multiplexing definitely helps with fingerprinting. Have you considered the more standard multiplexed protocols QUIC, or HTTP/2 over TLS? Why did you decide to go with Mux.Cool over other options?

**Comment by VictoriaRaymond** [comment]
V2Ray supports h2 over TLS too 😊. It was added after Golang finalized h2 package. So the main reason was toolchain.

Mux.Cool was introduced as a simple multiplexing feature. It does multiplexing only. There is no authentication and encryption. Mux.Cool was designed to work with Shadowsocks or VMess, as an additional optimization for short connections.

Here is a little bit about h2 in V2Ray. V2Ray has 3 layer of protocols: 
1. content processing (Mux.Cool)
1. authentication (Shadowsocks, VMess, Socks, HTTP, MTProxy, etc)
1. transport (WebSocket, h2, plain TCP/UDP, etc)

For example, one may configure an Mux + Shadowsocks + WebSocket combination. WebSocket is the outer most layer, and Mux is inner most.

The transport layer is mainly for interacting with other tools. The WebSocket or h2 traffic can be proxied through a Web server such as Nginx or Caddy. The traffic of the proxy can be hidden in this way.

There is no clear boundary between these three layers, e.g., Mux + VMess + WebSocket is more or less equivalent to VMess + h2, or h2 only. We keep our own protocols in order to iterate quickly and experiment many features as possible.

**Comment by justin223** [comment]
Guys, please add **obfuscation** to server and client implementations, as it's easy to be detected by GFW and the whole IP segment of VPS vendor will be blocked by GFW.

I've tried several vendor (Vultr, DO, Scaleway...) **without obfuscation** and only a few days working before my IP been blocked. Yes, it was shadowsocks that time that I deployed on my servers. Then I deploy **shadowsocks with simple-obfs plugin**, **both server side and client side**, everything goes well till now.

Please check on **shadowsocks-libev** and **simple-obfs** repos to find solution to this.
Sever side:
[shadowsocks-libev](https://github.com/shadowsocks/shadowsocks-libev)
[simple-obfs](https://github.com/shadowsocks/simple-obfs)

Client side:
[simple-obfs-android](https://github.com/shadowsocks/simple-obfs-android)
[simple-obfs](https://github.com/shadowsocks/simple-obfs)


****IT'S** URGENT** as the more users, the easier it is to be detected and blocked.

**Comment by kapitainsky** [comment]
I can confirm @justin223 comments. I am in China at the moment and as few months ago Outline worked without any issues now it stopped after few days. Most likely blocked as changing server IP solves it temporarily. At least as usage in China is concerned some extra obfuscation is needed.

**Comment by fortuna** [comment]
GoQuiet seems to be an even better alternative: https://github.com/cbeuw/GoQuiet/wiki/Advantages-over-similar-obfuscators.

I wonder if it's just a matter of time to block them though. TLS is easy to fingerprint:
https://tlsfingerprint.io/top/
https://github.com/LeeBrotherston/tls-fingerprinting

So the censor could write rules that block the specific fingerprint of simple-obf or GoQuiet if they are used widely enough. Also, it seems none of those solutions support UDP.

In any case, that's something we want to explore. There are other things to consider, like whether UDP is giving us away, in which case obfuscation wouldn't help.

@justin223 @kapitainsky : when you ran your unobfuscated servers, were they Outline servers? If not, did they have UDP enabled?

**Comment by justin223** [comment]
@fortuna It was Shadowsocks-libev port, and no UDP enabled, as IMO TCP connections are more reliable than UDP ones. 

When my IP was blocked, I cannot SSH to my server, and no ACK received from server side, so TCP connections cannot be established. But on the working server right now, I change cipher from the default "aes-256-cfb" to an AEAD cipher "aes-256-gcm", together with obfuscation feature, and no blocking till now.
![TCP SYN_RECV](https://user-images.githubusercontent.com/26566202/44069158-1d61a8b2-9fb0-11e8-966d-d1e80c41face.jpg)

**Comment by kapitainsky** [comment]
@fortuna The servers in my case are shadowsocks-libev 3.2.0 with UDP enabled

**Comment by testcaoy7** [comment]
I think GFW may has different sensitivity based on different physical location. In Shanghai, even insecure protocol like PPTP worked......

**Comment by fortuna** [comment]
@justin223 Good call on switching to the AEAD ciphers. The old ciphers make your server vulnerable to probing attacks, since the server couldn't really tell whether you knew the password.

@testcaoy7 in Outline we use chacha20-ietf-poly1305: https://github.com/Jigsaw-Code/outline-server/blob/69cf89c48e1e92ca38c88d0877758fc7f28e1196/src/shadowbox/server/managed_user.ts#L97
Among the safe ciphers it seems to be the fastest one if you don't have hardware acceleration and the only one that is mandatory in the [Shadowsocks current standard](https://shadowsocks.org/en/spec/AEAD-Ciphers.html).

**Comment by hadifarnoud** [comment]
@fortuna does this mean Outline will use AEAD? if not, is there a way to do it manually?

**Comment by studentmain** [comment]
@hadifarnoud emmmm...... They already use aead.

**Comment by fortuna** [comment]
@hadifarnoud The chacha20-ietf-poly1305 we use is AEAD

**Comment by hybtoy** [comment]
Nobody didn't mention shadowsocksr. Obfs is already part of the shadowsocksr.
@fortuna
Take a look to shadowsocksr, maybe you will find it useful for outline project.

**Comment by clementhk** [comment]
I can confirmed that it is UDP that gave it away.
I'm quite often in China and Dubai, they both detect UDP and block the server when using UDP (when using both pure UDP (Wireguard) or UDP + TCP (Shadowsocks)).

Right now I'm renting servers both inside and outside the countries, use udp2raw-tunnel + Wireguard to tunnel the servers, install Shadowsocks in outside servers, proxy Shadowsocks through the tunnel, and have the ports open in the inside servers, then use Outline clients. As they don't block UDP ports that are inside the country, this works well.

The downside of using udp2raw-tunnel (which uses raw socket to add TCP header on UDP package) was that it requires to add an iptables rule on the server side, but they finally has udp2raw-multiplatform that doesn't require iptables, but then we still need to use 2 ports, one for UDP and one for TCP, which is OK.

Now that Wireguard finally works well in all platforms that I care about (iOS as well 🙂), I believe the best solution is to use Wireguard + udp2raw, then all traffic goes through the FakeTCP port which still has all the cool things of using UDP.

Please do not remove Shadowsocks support in all the clients though, as it is right now the best solution we could get because system proxy solution of Shadowsocks cannot tunnel UDP packages.

**Comment by stefanovazzocell** [comment]
@fortuna How about combining multiple servers and automatically switching between then after a random amount of time (or bandwidth)?
This could spread the traffic a little and maybe draw less suspicion over a single server, hopefully making it harder to be sure that a server is used as a vpn. Or at least make blocking more costly.

Anyone has any thoughts on this? I am mostly thinking about the second comment made by @Tintac-CN ... Hopefully this idea can help mitigate detection. Imagine creating "clusters" and automatically provision them and have outline do some smart routing between them.

It would be cool to give server operators (or even users in some cases) the option to switch between different configurations and adapt to what works best for a specific situation. Maybe that could help people collect more feedback for outline (but unfortunately this last option will possibly increase the complexity for the server operators... I don't know if you rather keep it simple)

**Comment by clementhk** [comment]
> @fortuna How about combining multiple servers and automatically switching between then after a random amount of time (or bandwidth)?
> This could spread the traffic a little and maybe draw less suspicion over a single server, hopefully making it harder to be sure that a server is used as a vpn. Or at least make blocking more costly.
> 
> Anyone has any thoughts on this? I am mostly thinking about the second comment made by @Tintac-CN ... Hopefully this idea can help mitigate detection. Imagine creating "clusters" and automatically provision them and have outline do some smart routing between them.
> 
> It would be cool to give server operators (or even users in some cases) the option to switch between different configurations and adapt to what works best for a specific situation. Maybe that could help people collect more feedback for outline (but unfortunately this last option will possibly increase the complexity for the server operators... I don't know if you rather keep it simple)

Tried that in China and busted.

**Comment by stefanovazzocell** [comment]
@clementhk Alright, thank you for the info. How about compared to the 'usual'? Did it last longer before being detected? Did it get detected faster?

**Comment by testcaoy7** [comment]
Please give up Shadowsocks. In fact, there is another project called "Trojan". Trojan uses real TLS to encrypt traffic and firewalls will see these traffic as normal HTTPS.

Set up Trojan is very easy and certificates can be obtained freely from Lets Encrypt.

**Comment by studentmain** [comment]
@testcaoy But you still need `register a domain name for your server`(according to their manual). There're so many project use real TLS (even real HTTPS and can be proxy by a real HTTP server) and easy to setup, and they all need a domain name.

**Comment by testcaoy7** [comment]
@studentmain Oops...  I am sorry. I forget the domain name thing. Can we issue IP address based self-signed certificate to address the domain name issue?

**Comment by studentmain** [comment]
According to their document, we shouldn't do that: 

> Apply for or self-sign (**NOT RECOMMENDED**) an SSL certificate.

So, according to their document, the last option is following step:
1. buy a domain automatically
    - Can we do it with DO or GCP? 
    - How about self hosting server?
    - Buy domain from another provider? 
    - How if user already have a domain or just don't want to buy one?
2. then set DNS record
3. maybe deploy a fake website on server automatically?
    - What kind of fake site?
    - How if user already has a real website on it?
4. then apply for a free cert automatically
5. then deploy the software itself. 

Shouldn't be many technical problem problem here. As Outline-Manager can purchase server, it's easy for it to purchase a domain.

**Comment by testcaoy7** [comment]
@studentmain Maybe you can maintain a fork of trojan which uses PSK cipher suites. RFC5487 defines secure PSK cipher suites such as TLS_PSK_WITH_AES_128_GCM_SHA256. Certificates and domains are not needed in PSK cipher suites.

PS: I suggested supporting PSK cipher suites to the author of trojan before, but he/she decided not to support this feature because "it does not look like normal HTTPS behavior". I do not know if this is true. But I tried  a legacy PSK cipher (PSK with AES-CBC) with stunnel and it works very well.

**Comment by studentmain** [comment]
@testcaoy7 Uncommon cipher (specifically, PSK) is a fingerprint too.

**Comment by fortuna** [comment]
@testcaoy7 if you use a self-signed certificate, without a mechanism to validate it (we use a certificate fingerprint), then the censor can easily man-in-the-middle your connection.

If you want to use HTTPS, you can use [Caddy's forward proxy plugin](https://caddyserver.com/docs/http.forwardproxy). Caddy's handle the TLS certificate generation and renewal for you, and the plugin was designed to be probing-resistant. However, you still need a domain, and there's no user management UI. Not as easy as Outline

**Comment by fortuna** [comment]
**On rotating IPs**
One solution that I believe will be easy to implement, if you have a domain name :unamused:, is to make your domain resolve to multiple IP addresses, and make all the IP addresses point to your server. Then the client could rotate over the IPs for each connection.

One nice thing about domain names is that you can change the IP without resending keys, making it easier to recover from blocking. However the domain resolution may be still blocked, so we will need to be smart about that (e.g. using encrypted DNS, caching IPs, talking directly to authoritative, etc).

**Comment by fortuna** [comment]
**On using Single Port**
Outline now supports serving all users on a single port. We've heard from server admins that setting the port to 443 made their servers not be blocked anymore. I recommend people here try that and report back.

You can do that by adding `"portForNewAccessKeys":443` (don't forget the quotes) to `shadowbox_server_config.json` and calling `docker restart shadowbox`

**Comment by siavashs** [comment]
I tested port 443 on Digital Ocean yesterday and it was not reachable from Iran.

**Comment by faridcboy** [comment]
I have been using outline for a few months now and it usually took about 30 days for node IP to ban in Iran. however it has recently been faster. My last Vultr node got banned after 5 days with 20 users and total 40GBs of bandwidth usage which I assume is not high. 

As @fortuna previously mentioned, "One of the goals of making it easy to create a server was that you can do it whenever it gets blocked." and I believe this goal has been achieved by the Outline Project.
However, even there was some migration feature available for users, it would have been less time-consuming whenever the nodes get banned. My point is if we could transfer users keys from one (presumably banned) Outline Server to another fresh one with the least possible time, it could still worth to use Shadowsocks. Right now, I create each user  one-by-one in the new server which is nightmare to be honest.

I also like to mention that I have had a Cisco OpenConnect server which has been active for more than two years with more than 50 users and it has not been detected or banned even once. I am not sure about the underlying architecture of OpenConnect's data transmission but as a side note, I think it could be helpful too look into.

**Comment by kalhori124** [comment]
@fortuna  

If you use Outline ( Shadowsocks ) in Iran, China, Azerbaijan, and the United Arab Emirates, your VPS IP address will be blocked after a while. 

I am using OpenConnect, Stunnel, and Vmess protocols and there is not any problem with these protocols, but the installation of these protocols on the server side and client side is not easy as Outline VPNis for ordinary people.

**Comment by fortuna** [comment]
@faridcboy thanks for the feedback. I hear that migrating servers is not easy.
As a mitigation, you may set up a domain hostname for your server, so you don't need to resend invites if the IP gets blocked. You can specify the hostname in the manual installation. Example:
```
sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)" install_server.sh --hostname=myserver.com --keys-port=443
```

With that, the invitations will have "myserver.com" and you can update the IP freely.
In many cloud providers you can change the IP address of a server without having to recreate. On Google Cloud, you can create a new IP address and assign to the GCE instance. On DigitalOcean, you can use [floating IPs](https://www.digitalocean.com/docs/networking/floating-ips/).

**Comment by sysk** [comment]
+1 for using v2ray, it seems to work much better in China and it has the ability to route traffic through Cloudflare which means China would be forced to start blocking Cloudflare IPs if it managed to detect it (unlikely)

**Comment by kalhori124** [comment]
@fortuna Hi,

Can we have WebSocket and HTTP/2 in Outline for transferring data through a third-party gateway
like Cloudflare or other CDN providers?

With this, we can escape from the government firewall because they cannot block CDN providers.

**Comment by fortuna** [comment]
We could, but that would be a different protocol that is not backward compatible. We've been considering HTTP-based proxying, but one problem there is that you lose the performance benefits of UDP.

We haven't prioritized changes to the protocol because since we launched single port for all access keys the reports of blocked servers dropped dramatically.

**Comment by kalhori124** [comment]
@fortuna I agree with you that UDP has performance benefits but we can't use the Outline in Iran, China and a few other countries as they block VPS IP address!

This week I set up three VPSs from different locations and providers ( Vultr, DigitalOcean, Linode ) after installing Outline-Server and using Outline clients on a mobile phone and a PC the IP address of the VPS blocked by the Internet censorship firewall after one day with a little bandwidth usage about 500MB

After that, I cancel those VPS and create three new VPS again and set up OpenConnect, Stunnel, and V2ray and everything is OK as they use TCP

**Comment by Xananax** [comment]
I'm in Dubai, and I have very faint knowledge of how networks work (I do know my way around managing a VPS through ssh though, no problem). I've set up Outline both through the manager, on a droplet, and through the docker on my Linode VPS.

If I'm talking through Whatsapp/Skype/etc, any of my Outlines work for a couple of minutes, then all internet traffic gets cut off, through either of them (disconnecting my local Outline client restores internet).

Is there any set of instructions as to what to do for a n00b like me? Is there an alternative to Outline, even if the setup is more complex? As I said, I do not care much for ease of installation, as I have no trouble running software on my VPS or editing config files; all I hope for is not having to take decisions regarding options I don't have the faintest idea about, and have no time to learn either.

**Comment by stonedreamforest** [comment]
add v2ray please!

**Comment by hybtoy** [comment]
I switched to v2ray, because they ban shadowsocks very fast

**Comment by fortuna** [comment]
This is an issue from 2018 and a lot has changed since then.
Outline has implemented many protections against detection, including those reported by https://gfw.report/talks/imc20/en/.

We have reports that Outline is working a lot better now. Keep in mind that Outline is not the exact same as Shadowsocks. We have our implementation, configured in a specific way. That makes a difference.

Even if Outline still has some issues, we need fresh data. So I'll close this bug and we can discuss on a new thread if needed. Thanks all for the input.

**Comment by DonZheng** [comment]
Dear @fortuna ,

Sorry for asking a dump question. As you mentioned above that `We have our implementation, configured in a specific way.`, could you please advise that the major improvements are on the outline server side or client side?

Genuinely curious here, as I'm assuming outline as a smart server with 'dumb' client solution.

sincerely

**Comment by fortuna** [comment]
As shown in the research [How China Detects and Blocks Shadowsocks](https://gfw.report/talks/imc20/en/), the censor uses active probing to detect Shadowsocks servers. The probing may be triggered by packet sniffing, but that's not how the servers are detected.

Even though Shadowsocks is a standard, it leaves a lot of room for choices on how it's implemented and deployed.

First of all, you **must use AEAD ciphers**. If you are using stream ciphers, you are doing it wrong. It's very easy to break your encryption and detect your server. Outline has banned all stream ciphers, since people copy old examples to set up their servers. In fact, Outline picks the cipher for you, since people don't know how to pick it.

Second, you need **probing resistance**. Both shadowsocks-libev and Outline have added that. In the past, an invalid byte would trigger different behaviors whether it was inserted in positions 49, 50 or 51 of the stream, which is very telling. That behavior is now gone, and the censor can no longer rely on that.

Third, you need **protection against replayed data**. Both shadowsocks-libev and Outline have added such protection, which you may need to enable explicitly on ss-libev, but it's the default on Outline.

Fourth, Outline and clients using shadowsocks-libev now **merge the SOCKS address and the initial data** in the same initial encrypted frame, making the size of the first packet variable. Before the first packet only had the SOCKS address, with a fixed size, and that was a giveaway.

The censors used to block Shadowsocks, but Shadowsocks has evolved, and for now it's ahead again in the cat and mouse game.

**Comment by lgg** [comment]
@fortuna can we add this info to README or another docs? It's very valuable and useful.

**Comment by fortuna** [comment]
@lgg under way: https://github.com/Jigsaw-Code/outline-server/pull/843
