### ISSUE TITLE
Blacklist ports from being choosen by Outline Server when assigning access keys

### ISSUE THREAD

**Issue by nsuchy** [Jigsaw-Code/outline-server#301]
Just a quick suggestion. My organization runs a tunneling server with OutlineVPN being the primary choice. However we also run Wireguard and OpenVPN as secondary choices. It'd be nice to have the ability to block a specific port number from being picked randomly. It's not an issue today but as we add more and more users the risk of a conflict grows. Allowing administrators to make sure a port, or a range of ports, is never used would be an awesome feature. Thoughts?

**Comment by trevj** [comment]
@nsuchy Thanks for using Outline and for the suggestion. This is absolutely something we intend to offer in some shape or form - specifically, we've been thinking about how to run all access keys on a single port (easier firewall configs is one benefit).

**Comment by nsuchy** [comment]
@trevj Single port mode is a really good idea and I saw an existing issue however doesn't directly help existing severs unless they're prepared to contact every single user and give them new access keys (unless a seamless transition process is added to all client apps, maybe someone is willing to do this). I would have to contact every single user on my node and get them new access keys. I'm running SSH, OpenVPN, and Wireguard on non-standard ports, while the risk is low, a conflict could occur and need to be addressed. Thank you however for looking into this issue.

**Comment by fortuna** [comment]
@nsuchy We had an issue where we were not able to see that ports reserved outside the docker container were being used. That has been fixed since. We now [try to explicitly open the port](https://github.com/Jigsaw-Code/outline-server/blob/8aacfde7109b93d56457b42b15c58b210d88acc4/src/shadowbox/infrastructure/get_port.ts#L103) before deciding to allocate it to a key.

Please let us know if you see that issue again.
