### ISSUE TITLE
Hello! Whether to issue an API document

### ISSUE THREAD

**Issue by coding1618** [Jigsaw-Code/outline-server#343]
I am a programmer. I want to develop a manager program by myself through the API,I hope the official can provide some API operation documents，For example: add and remove users over HTTP protocol，Thank you, my English is not very good, I hope you can understand, 😁。

**Comment by alalamav** [comment]
Hi @coding1618, please see manager [API documentation](https://github.com/Jigsaw-Code/outline-server/blob/master/src/shadowbox/README.md#access-keys-management-api). Feel free to re-open this issue if you have questions.

**Comment by coding1618** [comment]
Thank you.

**Comment by coding1618** [comment]
Thank you

**Comment by coding1618** [comment]
How can I view user data traffic information?

**Comment by trevj** [comment]
@coding1618 We deploy Prometheus on the Outline server which records many statistics about the server. I'm sorry we don't have documentation for this yet but you will find Prometheus' web interface on `localhost:9090` on your server (because it only listens on localhost you'll have to use SSH forwarding to view on your workstation).

**Comment by auula** [comment]
thank.
