### ISSUE TITLE
Does Outline server use a secure DNS mechanism (DNS over STL, DNSCrypt, etc.) ?

### ISSUE THREAD

**Issue by shaomeng** [Jigsaw-Code/outline-server#366]
There is some effort in the community to push for the deployment of secure DNS mechanisms, including the [Intra](https://github.com/Jigsaw-Code/Intra) app which is also from Jigsaw. Does Outline currently perform DNS queries using one of these mechanisms? If not, is it in the plan to deploy in the future? 

Thanks,
Sam

**Comment by fortuna** [comment]
In Outline, DNS resolution is done by the client, not the server. That's because the clients operate as full system VPNs and intercept traffic at the IP layer. Resolution by the server only makes sense if you are using a Shadowsocks client that works as a system proxy, since then sockets can be created using domain names.

The Outline clients currently use standard unencrypted DNS over UDP, but all DNS traffic goes over the encrypted connection to the server. Your ISP won't see the unencrypted traffic, but your server will. In our threat model, you trust the server, so we haven't prioritized secure DNS, given all the other things we need to do.

**Comment by shaomeng** [comment]
This is excellent explanation, thanks @fortuna . I agree this isn't high priority, thus I'm closing it.

**Comment by bemasc** [comment]
@shaomeng Outline creates its own virtual network (VPN) on your Mac, with a different DNS server configuration.  When Outline is active, your macbook's configured DNS server will be changed from `192.168.1.1` to Outline's recommended DNS server, and queries will be routed through Outline.

**Comment by gasam9088** [comment]
Hello, please help! How can I do it? So I use openvpn, I configured it on the domain (dns) when state supervision blocks me, I just change the ip in the domain to a new one and all my clients automatically switch to another server! And how to do it on outline where to register DNS and how to transfer all clients to another hosting?
