### ISSUE TITLE
new keys have same port

### ISSUE THREAD

**Issue by sailosha** [Jigsaw-Code/outline-server#425]
I am wondering why the new key has the same port?
I think in the December we still can generate different ports.

**Comment by alalamav** [comment]
Hi @sailosha, we create all access keys in a single port in order to reduce the finger-printability of Outline servers. It also allows us to run a single Shadowsocks instance in the server.

This port is configurable in the install script and we are woking on making it configurable in the Outline manager.

Feel free to reopen this issue if you have further questions.

**Comment by karimi12** [comment]
how change default port number?

**Comment by jasonbohan** [comment]
> how change default port number?

you can find the config file in /opt/outline/persister-state/shadowbox_config.json .

than you can change the default port.
