### ISSUE TITLE
outline server - backup / restore

### ISSUE THREAD

**Issue by a1exus** [Jigsaw-Code/outline-server#450]
Hello World!

I used `Outline Manager` (1.2.2) on macOS to add new keys...

I can't locate my installation output (`apiUrl` or `certSha256`). How does one backs up configuration and restores it at another environment (without re-adding all keys)?

My `Outline Manager` is able to connect to `Outline Server` without any issue (everything works as intended).

Thanks in advance!

**Comment by alalamav** [comment]
Hi @a1exus, we are working on a feature to share server management. In the meantime, you can find your server's credentials at `opt/outline/access.txt` (unless it's a legacy server, in which case it should be in `/root/shadowbox/access.txt`). There you'll find the `apiUrl` and `certSha256`, which you can format as JSON and import it to another Outline Manager.

Hope this helps; feel free to reopen this issue if you have any questions.

**Comment by a1exus** [comment]
@alalamav I was able to backup & restore, thank you so much!

**Comment by Farzadmt** [comment]
Follow these steps and you will have no problem.
I did and got an answer

First, start the new server and go through all the installation steps of the outline.

Before pasting the API link in the outline of the server manager, do the following steps:

1- Copy user config with the following command:
scp -r root@Ip_old-Server:/opt/outline/persisted-state/shadowbox_config.json /opt/outline/persisted-state/shadowbox_config.json

2- Copy the config keys:

scp -r root@IP_Old-Server:/opt/outline/persisted-state/outline-ss-server/ /opt/outline/persisted-state/

3- Copy of consumption information and volume of users:

scp -r root@Ip_Old-Server:/opt/outline/persisted-state/prometheus/ /opt/outline/persisted-state/

4- Now copy the API link in the outline manager to establish the connection, you will see that all users are displayed with their usage volume.

5- Be sure to restart the server once before connecting users so that everything is done correctly.

6- Enjoy

**Comment by SignFinder** [comment]
> Follow these steps and you will have no problem. I did and got an answer
> 
> First, start the new server and go through all the installation steps of the outline.
> 
> Before pasting the API link in the outline of the server manager, do the following steps:
> 
> 1- Copy user config with the following command: scp -r root@Ip_old-Server:/opt/outline/persisted-state/shadowbox_config.json /opt/outline/persisted-state/shadowbox_config.json
> 
> 2- Copy the config keys:
> 
> scp -r root@IP_Old-Server:/opt/outline/persisted-state/outline-ss-server/ /opt/outline/persisted-state/
> 
> 3- Copy of consumption information and volume of users:
> 
> scp -r root@Ip_Old-Server:/opt/outline/persisted-state/prometheus/ /opt/outline/persisted-state/
> 
> 4- Now copy the API link in the outline manager to establish the connection, you will see that all users are displayed with their usage volume.
> 
> 5- Be sure to restart the server once before connecting users so that everything is done correctly.
> 
> 6- Enjoy

And one more step - change "portForNewAccessKeys" to old value in the current /opt/outline/persisted-state/shadowbox_server_config.json. New was generated with random and old clients will not be able to connect.
