### ISSUE TITLE
Comparison to shadowsocks ?

### ISSUE THREAD

**Issue by postadelmaga** [Jigsaw-Code/outline-server#50]
It is not clear to me if there is any advantage in term of security if compared to Shadowsocks ? 
It is basically the same and just more easy to setup ?

**Comment by bemasc** [comment]
Outline is currently based on the Shadowsocks protocol, so it has similar security properties to Shadowsocks.

**Comment by fortuna** [comment]
At the protocol level Outline is Shadowsocks. However, we've improved the user journey to make the user safer. Some examples:

- We choose a strong cipher for the user, so the doesn't choose a weak one.
- We generate random passwords, so the user don't set weak ones
- We use random ports, so the server is not fingerprintable by the pattern of open ports
- It's so easy to create servers that you can destroy and recreate them in order to make it harder to track your connections.
