### ISSUE TITLE
Your Outline Server was installed correctly, but we are not able to connect to it. Most likely this is because your server's firewall rules are blocking incoming connections. Please review them and make sure to allow incoming TCP connections on ports ranging from 1024 to 65535.

### ISSUE THREAD

**Issue by AsadKamran92** [Jigsaw-Code/outline-server#507]
Does Someone have any idea how to fix this issue?

**Comment by alalamav** [comment]
Hi @AsadKamran92, what cloud server provider are you using?
We have instructions on how to configure firewalls for AWS and GCP in the Outline Manager application.

**Comment by samascience** [comment]
if you are using your own server you might have to open the ports on the firewall / router

**Comment by sxy88** [comment]
Your Outline Server was installed correctly, but we are not able to connect to it. Most likely this is because your server's firewall rules are blocking incoming connections. Please review them and make sure to allow incoming TCP connections on ports ranging from 1024 to 65535.


When I deploy outline on my vmware virtual machine，and I've closed the firewall.
> Checking host firewall ...................... BLOCKED
OK

help me, ball ball le

**Comment by fortuna** [comment]
Stale issue
