### ISSUE TITLE
Long UI loading time of macOS app

### ISSUE THREAD

**Issue by testcaoy7** [Jigsaw-Code/outline-server#67]
I just get the Outline client software through Mac App Store and I have find that its UI takes long time to load (at least 3 min).

**Comment by trevj** [comment]
Sorry you've been having trouble with Outline, @testcaoy7. Can you please tell us what version of macOS you're running and roughly the specifications of your system?

**Comment by testcaoy7** [comment]
I am running the latest Outline from App Store and my macOS is the latest High Sierra.
My device is a 2017 model of MacBook Pro with Touch Bar.

Please note that I am using Outline from China.

**Comment by testcaoy7** [comment]
Both Outline server manager and client has the same issue.

**Comment by jab** [comment]
What do you see during the 3 minutes while it’s loading? E.g. Does the app UI appear but with invisible text?

(Reminder: All of Polymer’s paper elements depend on Polymer’s font-roboto element, which tries to download Roboto from fonts.google.com if it’s not locally installed (which is the default case on macOS). And fonts.google.com has been blocked in China. Worse, by default Safari/WKWebView used to paint invisible text while waiting forever for its web font to load, though it recently changed that to 3 seconds.

**Comment by jab** [comment]
(Sorry, the demons in my phone freaked out while I was editing that comment and closed the issue while I was mid-sentence (they must really hate web fonts). Amended and reopened.)

**Comment by jab** [comment]
@alalamav Using Polymer's [`font-roboto`](https://github.com/PolymerElements/font-roboto), which is what happens by default when you include the paper elements, rather than using [`font-roboto-local`](https://github.com/PolymerElements/font-roboto-local), is exactly the problem.

Take a look at font-roboto's html include:
https://github.com/PolymerElements/font-roboto/blob/master/roboto.html#L10

That relies on fonts.googleapis.com being accessible just so it can download the stylesheet that tells it which fonts to use.

Compare that to what font-roboto-local does:
https://github.com/PolymerElements/font-roboto-local/blob/master/roboto.html

That includes the `<style>...</style>` content inline locally, and references the required .ttf files that are included locally too:
https://github.com/PolymerElements/font-roboto-local/tree/master/fonts/roboto

This guarantees that on systems that can't access fonts.googleapis.com, they'll still have all they need locally to properly display `font-family: Roboto` -styled content, without painting it in invisible ink while the fonts.googleapis.com connection times out.

Looking at the [server-manager's bower.json](https://github.com/Jigsaw-Code/outline-server/blob/master/src/server_manager/bower.json) as well as [the client's](https://github.com/Jigsaw-Code/outline-client/blob/master/bower.json), I don't see any "dependencies" entries like
```json
"font-roboto": "PolymerElements/font-roboto-local",  # <- note the "local"
```
so it looks like this does not only affect "Product Sans" content, but all (paper styles' default) Roboto content too, hence the issues we're seeing that (IIUC) report that none of the UI shows up for 3 minutes.

**Comment by jab** [comment]
And just to make it clearer, the other approach I was advocating for above, involving [the empty-element version of font-roboto](https://github.com/StartPolymer/empty-elements/blob/master/roboto.html), i.e.
```json
"font-roboto": "StartPolymer/empty-elements#1.1.1"
```
is to ditch the Roboto nonsense altogether (it's just not worth it), and use the platform-specific system UI font available on each platform. This is the direction that a lot of sites have been going in now that major OSes are shipping their own high-quality, high-DPI system UI fonts, and it's much preferred to use a good thing available locally (even if it varies from user to user) than it is to have everyone get the same font but deal with the performance and connection-timeout risks of loading it remotely.
See e.g.
- http://markdotto.com/2018/02/07/github-system-fonts/
- https://furbo.org/2018/03/28/system-fonts-in-css/
etc.

**Comment by trevj** [comment]
@testcaoy7 Thanks again for the report. This issue should be fixed in https://github.com/Jigsaw-Code/outline-server/releases/tag/v1.0.7.
