### ISSUE TITLE
Command not found 

### ISSUE THREAD

**Issue by peterhou19** [Jigsaw-Code/outline-server#678]
Hi all, 

I was trying to create a new server on Google Cloud and copy-pasted the command line in outline server:

$ sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/m
aster/src/server_manager/install_scripts/install_server.sh)"

then I got this message 

-bash: wget: command not found

which is really weird to me as when I try to run the command in my existing serve it absolutely runs. So I'm really confused now.

**Comment by fortuna** [comment]
That's odd indeed. Is it available to root as well? That command runs as root.

**Comment by VishG28** [comment]
Hey, I tried doing the same and I'm having the same issue. Do you know what the reason could be? Also lmk if u need more info

**Comment by VishG28** [comment]
When I use an alternate command `curl -sSL https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh | bash`

It says this

![](https://i.gyazo.com/63fe6ceb0f88e1dd3ae089daf339c28c.png)

**Comment by VishG28** [comment]
I just figured out how to do it, you might wanna add this as an alternate way of installing. I typed
```
bash https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh | su
do bash
```
and then it worked

**Comment by Hasthikagirihagama** [comment]
> I just figured out how to do it, you might wanna add this as an alternate way of installing. I typed
> 
> ```
> bash https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh | su
> do bash
> ```
> 
> and then it worked

It doesn't work either

**Comment by VishG28** [comment]
Try installing just docker first and then try. https://blog.ssdnodes.com/blog/outline-vpn-tutorial-vps/

**Comment by Hasthikagirihagama** [comment]
According to the “Step 2. Installing the Outline VPN serverhow should I copy the next command because it does not show the root either after entering “sudo sudo systemctl status docker” it shows only as follows From: Vishruth GaurSent: Tuesday, December 8, 2020 9:49 PMTo: Jigsaw-Code/outline-serverCc: Hasthikagirihagama; CommentSubject: Re: [Jigsaw-Code/outline-server] Command not found (#678) Try installing just docker first and then try. https://blog.ssdnodes.com/blog/outline-vpn-tutorial-vps/—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by VishG28** [comment]
First do this `$ sudo curl -sS https://get.docker.com/ | sh`
Then this `$ sudo systemctl start docker`
Then this `$ sudo systemctl enable docker`
Then this `$ sudo sudo systemctl status docker`
If you get something similar to this then docker is running:
```
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─firewalld.conf
   Active: active (running) since Mon 2018-03-26 14:36:26 EDT; 4s ago
     Docs: https://docs.docker.com
 Main PID: 31232 (dockerd)
```
Then do this ```
bash https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh | su
do bash
```

**Comment by Hasthikagirihagama** [comment]
Ok thanks for the help, I found the reason for my error. It was because the wget is not installed.Anyway Thank you!! Again for the given support👍 From: Vishruth GaurSent: Tuesday, December 8, 2020 11:43 PMTo: Jigsaw-Code/outline-serverCc: Hasthikagirihagama; CommentSubject: Re: [Jigsaw-Code/outline-server] Command not found (#678) First do this $ sudo curl -sS https://get.docker.com/ | shThen this $ sudo systemctl start dockerThen this $ sudo systemctl enable dockerThen this $ sudo sudo systemctl status dockerIf you get something similar to this then docker is running:● docker.service - Docker Application Container Engine    Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)   Drop-In: /etc/systemd/system/docker.service.d            └─firewalld.conf    Active: active (running) since Mon 2018-03-26 14:36:26 EDT; 4s ago      Docs: https://docs.docker.com  Main PID: 31232 (dockerd) Then do thisbash https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh | su do bash —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ArdaIskender** [comment]
If you get this output; -bash: wget: command not found

then you might need to install wget with this;

`sudo apt-get wget`

say yes to confirmation and now you can use the command.

**Comment by ArdaIskender** [comment]
If you get this output; -bash: wget: command not found

then you might need to install wget with this;

`sudo apt-get install wget`

say yes to confirmation and now you can use the command.

**Comment by udayaccion** [comment]
> If you get this output; -bash: wget: command not found
> 
> then you might need to install wget with this;
> 
> `sudo apt-get install wget`
> 
> say yes to confirmation and now you can use the command.

This solution works perfectly. Thank you

**Comment by sch17** [comment]
seq: invalid floating point argument: ‘""’
Try 'seq --help' for more information.
date: invalid date ‘"+%Y-%m-%d@%H:%M:%S"’
bash: line 1: "": No such file or directory

Installation doesn't work
