### ISSUE TITLE
how to connet to the DigitalOcean droplet?

### ISSUE THREAD

**Issue by Simplici** [Jigsaw-Code/outline-server#68]
I have used the configuration for digital ocean, it worked like a charm. Good job.

But if i want to connect to the droplet to do some network configuration(limit the bandwidth for every IP), obvious, i need a user/password.

So the question is: what's the user and correspond password to connect to the droplet?

**Comment by indiespace** [comment]
I just started using Outline and DigitalOcean, I found if you go to the access section of your droplet. You will see a button to reset the root password. And then you can use the web console to access it if you would like to.

I assume you can just use the IP address associated with the droplet to connect using your own ssh client.

**Comment by trevj** [comment]
Thanks for reaching out to us, @Simplici. We are aware that it's not very easy right now to SSH into your DigitalOcean droplet. As @indiespace writes, the easiest way right now is to log in via the Access Console having first reset your droplet's root password - but unfortunately this isn't sufficient to enable access via a regular SSH client because the SSH server is configured to accept only key-based logins.

**Comment by fortuna** [comment]
FYI, the Manager v1.1.1 no longer disables SSH access with passwords, so you can use the password sent when you use the "Reset Root Password" option on your Droplet Dashboard on DigitalOcean. You can use your own SSH client. No need to use their console.
