### ISSUE TITLE
Feature request: API to reset traffic stat to zero

### ISSUE THREAD

**Issue by felixding** [Jigsaw-Code/outline-server#726]
I'm working on a new Outline service where I need to reset users' traffic stats monthly for accounting. Right now Outline's API has API to set/query traffic stat but not reset. Without this I can't do accounting properly.

Can you please add this feature?

If it's too much to ask, can you at least add `--web.enable-admin-api` to the Prometheus startup parameters so that I can reset (or do whatever I need with Prometheus) by using its API?

**Comment by fortuna** [comment]
Thanks for the request and for trying Outline.
Unfortunately we have few people and a number of other things we want to prioritize (dynamic keys, resilience, per-access key limits, selective proxying), so I think it will be hard for us to prioritize this issue anytime soon.

For anyone wanting to implement custom limits, I recommend querying the existing Prometheus instance at 127.0.0.1:9090/api/v1/query. Then you can delete keys as needed.

Keep in mind that the Outline scraper is configured to retain metrics for 31 days only:
https://github.com/Jigsaw-Code/outline-server/blob/c16594155a6f6097e78022a1615ba506f863d165/src/shadowbox/server/main.ts#L160

If you need longer retention, or need to calculate limits across multiple servers, I suggest you run your own Prometheus scraper and have it scrape 127.0.0.1:9092 (outline-ss-server process), or use federation:  https://prometheus.io/docs/prometheus/latest/federation/

I recognize that deleting keys when a limit is reached may not be ideal, so maybe we can provide an endpoint to enable/disable keys instead.

**Comment by felixding** [comment]
Thank you!

Just before I dive in to the code: does querying `127.0.0.1:9090/api/v1/query` allow me to query or reset transfer stat? If yes, where can I learn the keys you used in Prometheus, and can I query localhost if Prometheus is running in Docker?

Forgive my poor Docker knowledge. I'll search the how part if it's doable.

**Comment by HosseyNJF** [comment]
@felixding You can only query the bandwidth for each user using this endpoint; then you can handle limits manually by recognizing over-limit keys (using the query) and removing them from the outline server.

**Comment by fortuna** [comment]
You can query `127.0.0.1:9090/api/v1/query` from outside Docker, since docker runs using the host network. 

It seems Prometheus provides a delete series API that you could use: https://prometheus.io/docs/prometheus/latest/querying/api/#delete-series

By the way, we are planning to support a version of the [Shadowsocks Online Config](https://github.com/shadowsocks/shadowsocks-org/issues/89). This will allow you to decouple the config you send to the user from the backend access keys. In other words, you will be able to delete and recreate access keys for a user, without having the user reconfigure their device. To reset usage, you could delete an access key and create a new one, updating the online config with the information of the new key.

cc: @alalamav

**Comment by fortuna** [comment]
I tried this and it did not work. It seems we need to explicitly enable the admin APIs: https://prometheus.io/docs/prometheus/latest/querying/api/#tsdb-admin-apis

**Comment by felixding** [comment]
@HosseyNJF Removing/reissuing a key is not a great solution for me. I can't ask user to re-configure his laptop/phone once in a while.

@fortuna Yeah I've been following that issue. I assume you have to tweak the design of the Outline apps in order to support a config-subscription like feature? And yes, I'll need you to enable the API with `--web.enable-admin-api`. It should be just one line of change.

**Comment by felixding** [comment]
By the way, what is 'selective proxying'? Is it smart routing?

**Comment by fortuna** [comment]
@felixding Online configs allow you to decouple the Outline Access Keys from your user system.
You can keep a map user -> access key, then run a web server that serves the online config for that user.  If you delete and create a new access key, you just need to update the mapping, but the URL the user received doesn't need to change.

What I meant with selective proxying is the same as smart routing.

**Comment by fortuna** [comment]
PR submitted. We will have the admin API available in the next release, hopefully later this week. I wanna canary the server first.

One thing to keep in mind: this may not work as expected. That's because you will be deleting data from the database, but the server still has the current counter, which will be collected in the next Prometheus scrape.

The calculation of "data in the past 30 days" happens by subtracting the counter value for 30d ago from the counter now. Even if you delete all points in between, the difference will be the same (well, not really, it will lose the tracking of restarts, so you'll see a smaller counter)

Here is a workaround:
1. Restart outline-ss-server (killing it should work, it's restarted automatically, though it will kill all open connections). This will reset the in memory counter to zero
1. Delete the time series.

**Comment by felixding** [comment]
Thanks.

I see.

Killing shadowsocks connection will make users complain so I can't do it.

I think I can remember the counters in the database and do the substraction by myself (as exactly how you calculate the usage).

**Comment by felixding** [comment]
I ended up scraping Outline's exporter from my Prometheus server:
 
- Redirect a port to 127.0.0.1:9092 using iptables
- Scrape Outline's exporter
- Record the transfer_reset_at timestamp
- Calculate the transfer consumption by subtracting current transfer value with the one at transfer_reset_at

**Comment by sobhan-m94** [comment]
@HosseyNJF 
سلام.
حسین میتونی راهنمایی کنی چطور مصرف یه کلید رو صفر کنم ؟ با promethus ؟
نمیخوام حذف بشم. چون بعدش مجبورم کلید جدید به کاربر بدم.
راهی هست مصرفشو صفر کنم ؟
الان بعد از ۳۰ روز شروع به کم کردن میکنه. اگر بشه صفرش کرد و دوباره مصرف رو محاسبه کنه خوبه.

**Comment by maysamgamini** [comment]
Hi @felixding 
Hope you are doing well. 

I'm going to develop a microservice for outline user management, I would truly appreciate it if you could share with me some of your findings regarding user management.

1. Were you able to limit the number of IPs/Users that can connect? if so, what steps did you take?
3. Were you able to calculate the traffic outside the 30-day time frame? if so, what steps did you take?

could you please add more details to this comment of yours:
I ended up scraping Outline's exporter from my Prometheus server:

Redirect a port to 127.0.0.1:9092 using iptables
Scrape Outline's exporter
Record the transfer_reset_at timestamp
Calculate the transfer consumption by subtracting current transfer value with the one at transfer_reset_at

**Comment by maysamgamini** [comment]
another question here, it looks like Configure Custom Retention is a feature request that everyone is asking, does the outline server remove the data limits logs from the server?
