### ISSUE TITLE
ISP blocks Outline connections 

### ISSUE THREAD

**Issue by 7urkm3n** [Jigsaw-Code/outline-server#745]
Somehow my ISP (internet service provider) blocks connections to the server.

Is there specific thing that can be block or am i missing something  ?

And interesting part, on some android devices are working, and some of not.

Android: Yes and No
IOS: always No

**Comment by yakovmanshin** [comment]
Have you checked whether the port your Outline server uses for client connections is open on the network?

I had a problem similar to what you described, and it turned out my school Wi-Fi had only the basic ports (such as 80, 443, etc.) open, while everything beyond 1024 was closed for “security reasons.”

**Comment by 7urkm3n** [comment]
@yakovmanshin Yes, i do have 4/5 outline servers. All of them different ports, and still the same issues. I believe, its from ISP and router issue. Only the problem, It works on android and doesnt work on IOS :D

**Comment by williamgh2019** [comment]
You can try to setup Floating-IP on your server.

**Comment by fortuna** [comment]
What Android and iOS client versions are you using?
