### ISSUE TITLE
Digital Ocean website became blocked in China

### ISSUE THREAD

**Issue by xiaomeng80** [Jigsaw-Code/outline-server#871]
I used to be able to visit www.digitalocean.com from inside China to spin up VPS for outline servers, now the domain seems to blocked already according to this [GreatFire.org measurement](https://twitter.com/NP_tokumei/status/1381792370849550338). This makes it harder to spin up new droplets when an outline server's IP gets blocked :(

**Comment by JonathanDCohen** [comment]
We're keeping an eye on it.  We have some evidence that it's not completely blocked as of now.  If the block becomes more severe, depending on how its blocked we may be able to try some workarounds.  

For now, you can't spin up a new server from the Manager?

**Comment by williamgh2019** [comment]
Use float IP from DigitalOcean

**Comment by alexlii1971** [comment]
Hello,

Today, I found our outline server was blocked, and I lost connections, and when I try to create a new server,  I encounter errors as below:

After "authorise application", it will show 
```
Oh no! Sammy ate the page you were looking for.
Head back to the control panel.
```

and please check the screenshot:
![1628587380186](https://user-images.githubusercontent.com/15896194/128842786-99e1c6c0-5645-4d22-b4ba-b930084994a5.jpg)

But when I try create server on Vultr, it will show errors on ubuntu 21.04  x64, 20.10  x64, 20.04  x64, 18.04  x64 as below:

`root@outline_VPN:~# sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)"
> Verifying that Docker is installed .......... NOT INSTALLED
> Would you like to install Docker? This will run 'curl https://get.docker.com/ | sh'. [Y/n] y
> Installing Docker ........................... Docker installation failed, please visit https://docs.docker.com/install for instructions.

Last error: # Executing docker install script, commit: 0e685c6ac0bddd7b2ba7bcaaeb519746ad249a29
+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sh -c curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
+ sh -c echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu bionic stable" > /etc/apt/sources.list.d/docker.list
+ sh -c apt-get update -qq >/dev/null
W: GPG error: https://download.docker.com/linux/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7EA0A9C3F273FCD8
E: The repository 'https://download.docker.com/linux/ubuntu bionic InRelease' is not signed.

Sorry! Something went wrong. If you can't figure this out, please copy and paste all this output into the Outline Manager screen, and send it to us, to see if we can help you.
Full log: /tmp/outline_logCpS
root@outline_VPN:~# `

Please let me know if there is an alternative way to fix the errors, thanks.

**Comment by alexlii1971** [comment]
Hi,

The following methods work fine:


apt install docker.io

Then

sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)"


By this way, it will work on Vultr, but not test on digitalocean yet.

Thanks

**Comment by fortuna** [comment]
DigitalOcean is accessible again according to GreatFire: https://en.greatfire.org/https/www.digitalocean.com
