### ISSUE TITLE
Unable to add new server or remove old one

### ISSUE THREAD

**Issue by devhops** [Jigsaw-Code/outline-server#873]
I have created a new outline server. That works great.

When I open the Manager to add it, the application hangs. Eventually it times out, but I cannot remove the old server, or add a new one. The application just hangs. I have tried uninstalling but this old instance is never removed.

It would appear others on Reddit are reporting similar issues.

https://www.reddit.com/r/outlinevpn/comments/mqo0g6/i_cannot_remove_the_server_from_outline_manager/ 

For me this is a show stopper as I cannot release it to the client until I can manage it.

I am running MacOS 10.15.7. The Outline Manager version is 1.7.2 (1.7.2.4399).

**Comment by JonathanDCohen** [comment]
Hey there!  Sorry for the delay.

So reading your post, you created the server separately, not from Outline Manager?  Are you able to run the Manager in debug mode and see what comes up in the console?

**Comment by dylankeyes** [comment]
I'm having the same problem trying to remove a server from the Manager that was created in the Manager. This error shows up in the console:

`C:\Users\USER\AppData\Local\Programs\outline-manager\resources\app.asar\node_modules\@sentry\browser\dist\helpers.js:91 Uncaught TypeError: Cannot read property 'forget' of undefined
    at Lc.forgetServer (app.ts:120)
    at HTMLElement.<anonymous> (app.ts:176)
    at HTMLElement.sentryWrapped (C:\Users\USER\AppData\Local\Programs\outline-manager\resources\app.asar\node_modules\@sentry\browser\dist\helpers.js:74)
    at HTMLElement.removeServer (outline-server-view.js:1125)
    at HTMLElement.<anonymous> (template-stamp.js:136)
    at HTMLElement.sentryWrapped (C:\Users\USER\AppData\Local\Programs\outline-manager\resources\app.asar\node_modules\@sentry\browser\dist\helpers.js:74)
    at Qn (gestures.js:669)
    at ei (gestures.js:1065)
    at Object.click (gestures.js:1024)
    at HTMLElement.Kn (gestures.js:457)
    at HTMLElement.sentryWrapped (C:\Users\USER\AppData\Local\Programs\outline-manager\resources\app.asar\node_modules\@sentry\browser\dist\helpers.js:74)`

**Comment by JonathanDCohen** [comment]
That's no good.

Thanks for the call stack, @dylankeyes.  We recently did a refactor around this code so I'm wondering if we didn't miss a step in server creation somewhere.  I'm going to take a look at this tomorrow.

Are you having an issue with the app hanging?  Can you add a server still?

**Comment by dylankeyes** [comment]
@JonathanDCohen I just tested adding and removing a new server and can narrow things down now: the Manager is unable to remove unreachable servers. As long as the Manager's connected to a server it can be removed but as soon as it's not (e.g. the server is shut down or you disconnect your Manager computer from the internet) the button stops working.

There's no app-wide hanging, so I guess the Windows and Mac issues are different, but I wonder if they're related because it does look hang-like when I hover over an unreachable server in the hamburger menu (mouse turns into a spinning blue circle) -- even though the app otherwise still functions.

Hope that helps!

**Comment by maungthuu** [comment]
Same here on my mac. I can't remove Unreachable Servers. Spinning icons can't stop spinning.
