### ISSUE TITLE
Can you add an option for dynamic IP?

### ISSUE THREAD

**Issue by FSElias** [Jigsaw-Code/outline-server#88]
Hello,
please, can you add an option for domain instead of public IP address?

**Comment by bemasc** [comment]
Do you have your own domain name for the server, or would you like the outline-server software to acquire a new domain name for you?

**Comment by FSElias** [comment]
Sorry if I didn't make myself clear, I have my own already, I meant to give an option to put my domain instead of automatically detect the public IP address which in my case is changing every some period of time

**Comment by bemasc** [comment]
OK, thanks for the clarification.  For your information, the client software already supports access keys that contain a domain name instead of an IP address, so if you want you can manually modify the access keys and this should work today.

This issue reflects the feature request to enable the server to generate such access keys itself.

**Comment by fortuna** [comment]
This is where we set the host in the management service response that is used for the invitations:
https://github.com/Jigsaw-Code/outline-server/blob/eb9a6bfc4b967f28ade47bd7c1da820e21039c07/src/shadowbox/server/libev_shadowsocks_server.ts#L73

The `publicAddress` comes from `process.env.SB_PUBLIC_IP` and is set here:
https://github.com/Jigsaw-Code/outline-server/blob/eb9a6bfc4b967f28ade47bd7c1da820e21039c07/src/shadowbox/server/main.ts#L62

It seems we don't use the public address anywhere else in (e.g. LibevShadowsocksServer doesn't restrict the IP the SS instances should listen), so it should be safe to start the server with `SB_PUBLIC_IP=mydomain.com`.

It would be nice to have a way to modify this after the server is created, and a way to have this done on the Manager.

**Comment by GeniusPeterJiang** [comment]
When I do that, I got "Invalid IP lookup result: mydomain.com"

**Comment by fortuna** [comment]
@alalamav Any idea why the message?

**Comment by fortuna** [comment]
@GeniusPeterJiang where do you get that message? In the server installation? On the client?

**Comment by GeniusPeterJiang** [comment]
Thx for your reply. I got the error message when I installed the server. For now, I just use the public IP address for installation and use domain when I send out the client link. And so far both server and clients are happy and didn’t complain any error

**Comment by fortuna** [comment]
Would you mind sharing the installation command you used (sanitized of any personal information) to help us investigate further?

**Comment by GeniusPeterJiang** [comment]
{ export SB_PUBLIC_IP=mydomain.com; wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh | bash; }

**Comment by fortuna** [comment]
@GeniusPeterJiang I'm sorry about that. The problem are these lines:
https://github.com/Jigsaw-Code/outline-server/blob/01e6b20642792aa0b039e755925552b11a06892c/src/server_manager/install_scripts/install_server.sh#L383-L387

If you download the script and remove them, your installation should work.

@alalamav : I think we should skip that test if we don't run the ipinfo.io lookup. Also I realize that we are failing on IPv6. If we want the server to use IPv4 (because many clients don't support IPv6), it's better to force curl to do the lookup with IPv4 with `--ipv4` and don't enforce IPv4 anywhere else, so we don't prevent the use of IPv6 (or domains, for that matter).
