### ISSUE TITLE
Unexpected counter reset in Prometheus

### ISSUE THREAD

**Issue by felixding** [Jigsaw-Code/outline-server#893]
Hi,

I've noticed there was a counter reset in Prometheus. I don't know why it happened. I didn't reboot the server at the time.

![Screenshot from 2021-05-05 14-39-08](https://user-images.githubusercontent.com/111456/117101230-b0faae00-adb0-11eb-9e79-0e386e2ec396.png)

**Comment by JonathanDCohen** [comment]
Hey there.  Thanks for reporting the issue!

This happened right around the time that we pushed a new version of Shadowbox, so I'm wondering if there isn't some correlation here.  I'm gonna run some experiments and see if I can't reproduce.

**Comment by JonathanDCohen** [comment]
So what's going on here is that Prometheus Counters reset to 0 when the process resets.  Prometheus provides the [increase](https://prometheus.io/docs/prometheus/latest/querying/functions/#increase) function in PromQL in order to compensate for this reset.  So if you do `increase(shadowsocks_data_bytes{status="OK", dir=~"c<p|p>t"}[30d])` , for example, you'll get the traffic from the last 30 days.
