### ISSUE TITLE
Stuck on "Enter billing information..." page when trying to connect to DigitalOcean account

### ISSUE THREAD

**Issue by psun3** [Jigsaw-Code/outline-server#904]
Hi everyone,

After I have setup a server in DigitalOcean that's up and running, I see this "Enter billing information..." screen when trying to log in my DigitalOcean account in Outline Manager. 

- I have contacted DigitalOcean and made sure my account has no problem and billing info is correct. 
- I have uninstalled and reinstalled Outline Manager on Windows and MacOS and both are still showing the same screen of "Enter billing information..."
- I have signed out and signed in my DigitalOcean account in Outline Manager
Nothing above solved the issue.

DigitalOcean support suggested reaching out for help here... I wonder if any of you are experiencing the same odd behavior and if there is any way to solve this?

Thanks!!
![Screen Shot 2021-05-26 at 4 27 52 PM](https://user-images.githubusercontent.com/84881680/119743679-4254c180-be3f-11eb-8873-ad8184dfce78.png)

**Comment by MintBlitz** [comment]
I have the exact same problem, no matter which platform or computer I'm using, with my digitalocean servers it gets stuck at "Enter billing information..."
I start the Outline Manager app, select the DigitalOcean tile and click "Setup", it opens digitalocean.com then I click "Authorize application", I go back to the app and it says "Enter billing information..." which I did long ago already. Same on Windows also. Can't solve the problem. 
I have a 100$ free trial I don't know if it's linked, I also credited my own 25$ so I'm not sure what's the matter here because it was working fine for a couple of days. Could be also related to the numbers of servers in use, when it was working fin I only had one digitalocean server.

**Comment by MintBlitz** [comment]
It's quite a criticial bug because we don't have access to our keys anymore or even the data comsumption status of the keys already shared.

**Comment by psun3** [comment]
@MintBlitz Yes this issue is such a pain b/c we could not longer access the keys. I did not have the $100 trial. I started payment using my Paypal account then I added my credit card info and bought some Digital Ocean credit using that payment method. This issue still persists.

**Comment by MintBlitz** [comment]
"Good news", I located the issue. 
As I suspected at first, the number of maximum droplets (servers) on Digitalocean is the issue. That's why I contacted them couple days ago to increase that limit which they agreed to. 

I though it was done and the problem was still there so I was confused. 
Today I went back to my Digitalocean account and saw that the limit still says 3 maximum. 
So I sadly decided to destroy one of my droplet for the good of a test and it worked, now Outline Manager is fully functionning with 2 droplets (servers).
So I will go back and push DigitalOcean to increase that limit for real this time, while waiting for an update from Outline/DigitalOcean.

So at the moment increasing the limit of droplet or using only 2 droplets are the only workarounds for that particular issue.

<img width="1680" alt="Screen Shot 2021-06-02 at 10 48 54" src="https://user-images.githubusercontent.com/85206511/120418115-86414c80-c392-11eb-99c0-063a88d11245.png">

**Comment by psun3** [comment]
@MintBlitz you are right! I had droplet limit of 1, and just got bumped to 5. Without adding any droplet (I have only 1), I no longer see the "Enter billing information" screen. I have access to the keys and functional pages within Outline Manager. Thank you @MintBlitz for sharing this solution!!

**Comment by psun3** [comment]
I'm closing this issue since this workaround has provided what I need for the moment and I'm not sure if this glitch is caused by Digital Ocean or Outline Manager.
