### ISSUE TITLE
Possible to change API port on an existing Outline server?

### ISSUE THREAD

**Issue by felixding** [Jigsaw-Code/outline-server#966]
I'd like to change the API port on one of my Outline servers. Is it possible?

Couldn't find any config file for this. After some searching, I found the `SB_API_PORT`. Can I simply set this ENV var and restart the docker container? Or is there any official way to do this?

Thanks!

**Comment by fortuna** [comment]
Yes, setting the `SB_API_PORT` and restarting should work.

**Comment by fortuna** [comment]
Oh, it's not easy to change a Docker environment variable though!

First, you need to dump them:
```
docker inspect --format '{{range .Config.Env}}{{println .}}{{end}}' shadowbox | grep SB_ > /opt/outline/run.env
```

Then edit `run.env` to update `SB_API_PORT`.

Restart the container with the new environment (like in the [install script](https://github.com/Jigsaw-Code/outline-server/blob/ef56c51905d1d5563d79adc297d4df950ada4ebd/src/server_manager/install_scripts/install_server.sh#L292)):
```
docker stop shadowbox && docker rm shadowbox && docker run -d --name shadowbox --restart always --net host --label 'com.centurylinklabs.watchtower.enable=true' -v /opt/outline/persisted-state:/opt/outline/persisted-state --env-file=/opt/outline/run.env quay.io/outline/shadowbox:stable 2>&1 >/dev/null
```

You will need to keep the `run.env` file around forever, since it will be read on every restart done by watchtower.
