### ISSUE TITLE
Restricting the VPN adapter to a single IP or subnet

### ISSUE THREAD

**Issue by markomitranic** [Jigsaw-Code/outline-server#969]
Hey there team,

I am using OpenVPN to securely connect to my development server ([read here if interested](https://medium.com/homullus/remote-development-or-how-i-learned-to-stop-worrying-and-love-the-mainframe-90165147a57d)) and the main feature why i chose OpenVPN over Outline was that i was able to restrict the adapter to a single IP or a subnet.

```
route-nopull 
route 192.168.0.1 255.255.255.255
```

For me, this allows me to use the rest of the internet as I normally would, while being able to cover only a certain IP with a VPN. Is there a similar feature in Outline? If not, are you interested in this type of thing, I would gladly contribute.

**Comment by LaudateCorpus1** [comment]
If you find the time to run a full-range network adaptability run-time machine on GKE you can find that its a bit faster on the Google based network. Though you might need Ruby to adapt the VMWare + the sudo-adapters.

**Comment by markomitranic** [comment]
Lol, I'm pretty sure that they just register a network interface adapter for a specific subnet mask on my local machine. Has nothing to do with the upstream. 

Thanks anyway, not going to be using it

**Comment by LaudateCorpus1** [comment]
I meant Google Fi and Google Cloud servers in general work faster on outline since its a Jigsaw applet and it was build on their backbone (possibly, don't quote me) from a Google X project, I forget some of the details. Imma look into OpenVPN. 
Still good call, I have been doing similarly in my personal/private app edits, but would suggest carrying the Google Cloud settings .yml to use with any API to directly route into the Service. I wouldn't fill out the template and put my info on the Shell for y'all to use. Thank you for the privacy notices. Appreciate your guy's work on the Open Source Software && Wiki's.
