### ISSUE TITLE
Install ok ,but the manager settings can not be done

### ISSUE THREAD

**Issue by PutinLu** [Jigsaw-Code/outline-server#97]
I use vultr install outline server ,os is centos ,but the manager settings can not be done .Please tell me how to get this done.

error message:
Your Outline Server was installed correctly, but we are not able to connect to it. Most likely this is because your server's firewall rules are blocking incoming connections. Please review them and make sure to allow incoming TCP connections on ports ranging from 1024 to 65535.

**Comment by YuanHaoTomo** [comment]
Hello, I also encountered the same problem. Will you solve it? I'm using google cloud. Opening the ports in the control panel still prompts this error.

**Comment by krrisztian** [comment]
After the installation, you have to open ports on the firewall of your provider. On Google Cloud, it is under VPC Network->Firewall rules and create a new one.
But firstly, on Google Cloud, you have to give your instance a network tag (I used "outline") and you have to crete the following firewall rule under Firewall rules:
-Ingress
-allow IPs: 0.0.0.0/0
-Ports: tcp:1024-65535;udp:1024-65535; (if you want to open all of them, you can also open up only the ports that are required by the first key //outline installer tells you which ones when it finishes)
-network tags: outline (use the same "tag" as you used in your instance so that the cloud knows which instances to apply the rule to)

hit save, wait for it to be applied and try to connect!

**Comment by CliffLeopard** [comment]
I also encountered the same problem, and I stoped the firewall and iptables, but it was still not work. How can I fix it?

**Comment by todatamining** [comment]
You need to create a firewall rule in Vultr->Settings->FireWall->(manager)

Add the following rule:

Action	Protocol	Port (or range)	Source
accept	UDP	1024 - 65535	0.0.0.0/0
accept	TCP	        1024 - 65535	0.0.0.0/0
accept	TCP	         22                   your ip addres

Then apply this rule to your instance

**Comment by YuanHaoTomo** [comment]
I was encountering this error in google vps installation, but my firewall rule settings are not wrong. The next solution was to remove the vps instance and install it after recreating a new instance.

**Comment by danielchim** [comment]
Hello, I also encountered the same problem. Will you solve it? I'm using localhost machine with CE (or U instead)NT os in vmware workstation . What can I do?

**Comment by belous** [comment]
Hi guys.
So, I have installed outline on my instance (on vultr) with ubuntu 16.04 and I faced with the same issue in Outline Manager.
But this is because I manually enabled and configure firewall on my instance.
So here how it was configured:
```
vpn@vm0:~$ sudo ufw status
Status: active

To                         Action      From
--                         ------      ----
OpenSSH                    ALLOW       Anywhere
22                         ALLOW       Anywhere
443/udp                    ALLOW       Anywhere
OpenSSH (v6)               ALLOW       Anywhere (v6)
22 (v6)                    ALLOW       Anywhere (v6)
443/udp (v6)               ALLOW       Anywhere (v6)
```
And, of course, I'm getting the error in Outline Manager.
But at the end of installation of outline on the instance there was a very useful message:
```
If you have connection problems, it may be that your router or cloud provider
blocks inbound connections, even though your machine seems to allow them.

- If you plan to have a single access key to access your server make sure
  ports XXXXX and YYYYY are open for TCP and UDP on
  your router or cloud provider.
```
And here what I've done to get outline manager works:
```
sudo ufw allow XXXXX,YYYYY/udp
sudo ufw allow XXXXX,YYYYY/tcp
```
That's it. Now it works. I hope it will help someone :)
Have a great day!

**Comment by baamin84** [comment]
Hello,

I'm hosting ubuntu 16.04 on VMware but when i try to connect i get the same error. Dispite i've open up the ports required... Can you please help???

Thanks!

To                         Action      From
--                         ------      ----
1024                       ALLOW       Anywhere                  
1024:65535/tcp             ALLOW       Anywhere                  
1024:65535/udp             ALLOW       Anywhere                  
39601/tcp                  ALLOW       Anywhere                  
1024,65535/tcp             ALLOW       Anywhere                  
1024,65535/udp             ALLOW       Anywhere                  
1024 (v6)                  ALLOW       Anywhere (v6)             
1024:65535/tcp (v6)        ALLOW       Anywhere (v6)             
1024:65535/udp (v6)        ALLOW       Anywhere (v6)             
39601/tcp (v6)             ALLOW       Anywhere (v6)             
1024,65535/tcp (v6)        ALLOW       Anywhere (v6)             
1024,65535/udp (v6)        ALLOW       Anywhere (v6)      


You won’t be able to access it externally, despite your server being correctly
set up, because there's a firewall (in this machine, your router or cloud
provider) that is preventing incoming connections to ports 39601 and
.

**Comment by baamin84** [comment]
Hello,

I'm hosting ubuntu 16.04 on VMware but when i try to connect i get the same error. Dispite i've open up the ports required... Can you please help???

Thanks!

To                         Action      From
--                         ------      ----
1024                       ALLOW       Anywhere                  
1024:65535/tcp             ALLOW       Anywhere                  
1024:65535/udp             ALLOW       Anywhere                  
39601/tcp                  ALLOW       Anywhere                  
1024,65535/tcp             ALLOW       Anywhere                  
1024,65535/udp             ALLOW       Anywhere                  
1024 (v6)                  ALLOW       Anywhere (v6)             
1024:65535/tcp (v6)        ALLOW       Anywhere (v6)             
1024:65535/udp (v6)        ALLOW       Anywhere (v6)             
39601/tcp (v6)             ALLOW       Anywhere (v6)             
1024,65535/tcp (v6)        ALLOW       Anywhere (v6)             
1024,65535/udp (v6)        ALLOW       Anywhere (v6)      


You won’t be able to access it externally, despite your server being correctly
set up, because there's a firewall (in this machine, your router or cloud
provider) that is preventing incoming connections to ports 39601 and
.

**Comment by PutinLu** [comment]
I turned the firewall down, but still not work.I've tried centos and ubuntu, both were  not success.So I turned to use ssr.Google "ss一键安装脚本".Sorry, I don't know how to say it in english。
我关掉了防火墙，仍然出现这个错误。我在centos和ubuntu上都做了尝试，但是都没有成功。最后我是改用了ssr。搜索ss一键安装脚本。

**Comment by ffffyyc** [comment]
If you have connection problems, it may be that your router or cloud provider
blocks inbound connections, even though your machine seems to allow them.

Make sure to open the following ports on your firewall, router or cloud provider:
- Management port XXXXX, for TCP
- Access key port YYYYY, for TCP and UDP
-------------------------------------------------------------------------
I'm using vultr centos7,and i have solved firewall problem after type command like these,

firewall-cmd --zone=public --add-port=XXXXX/tcp --permanent
firewall-cmd --zone=public --add-port=YYYYY/tcp --permanent
firewall-cmd --zone=public --add-port=YYYYY/udp --permanent

**Comment by jhrtn** [comment]
I also couldn't get past this stage today with GCP. After a couple of hours of troubleshooting, setting up different instances in different locations I realised that it was because I had 12vpn running on my local machine which was seemingly blocking the Outline Manager client from sending the request

**Comment by BlackPoint-CX** [comment]
> On Vultr:
> 
> You need to create a firewall group in Vultr->Settings->FireWall->(manager)
> 
> Add the following rule for the firewall group:
> 
> ```
>  Action	Protocol	Port (or range)	       Source
>  accept	UDP         1024 - 65535          0.0.0.0/0
>  accept	TCP	        1024 - 65535           0.0.0.0/0
>  accept	TCP	         22                            your ip addres
> ```
> 
> Then apply this group to your instance

I used the same steps but not work.

**Comment by 0000ali9999** [comment]
i did all no result ubunto 22 from iran

**Comment by afshin-ai** [comment]
Hi @0000ali9999, The issue is not related to geographical location. For example, I have a similar issue in Australia. I think it's a bug in Outline.

**Comment by mzaprudin** [comment]
I tried to setup outline-server to oracle vps
I use ubuntu 20.04 minimal
ufw is disabled
I opened ports requested after installation in VCN console for TCP and UDP protocols
But unfortunately it doesn't work, I have the same trouble " Please review them and make sure to allow incoming TCP connections on ports ranging from 1024 to 65535."

I tried to install "tailscale" VPS server and it works without any additional netwrok configuration
So it isn't about firewall inside OS or VCN setup

I like outline and it would be great if this issue is solved

**Comment by arkh91** [comment]
> Hi @0000ali9999, The issue is not related to geographical location. For example, I have a similar issue in Australia. I think it's a bug in Outline.

پورت باز کردی؟

**Comment by Slava-Shchipunov** [comment]
> Я заставил его работать на vultr, запустив:
> 
> ```shell
> sudo ufw allow 1024:65535/tcp
> sudo ufw allow 1024:65535/udp
> ```

Thanks it worked for me

**Comment by AlexandrMers** [comment]
I understand that I answer too late

But you can check list of docker containers after install in your vps, you would see that the container "shadowbox" is crushing, and you can see its logs. I've just seen that container is throwing error with some sings of "localhost", I tried to add "127.0.0.1 localhost" to /etc/hosts and after that I ran all the install of outline again, and I've seen the container "shadowbox" is working well. And connection of outline manager is successfully
